
import type { Drink } from './types';
import { Coffee, CupSoda, Leaf, Zap, Pill, Beaker } from 'lucide-react';
import { sugars } from './sugars';

const FL_OZ_TO_ML = 29.5735;

const baseDrinks: Omit<Drink, 'id' | 'icon'>[] = [
  // Coffee (Generic)
  { name: 'Brewed Coffee', category: 'Coffee', caffeine: 95, size: 240 },
  { name: 'Espresso', category: 'Coffee', caffeine: 64, size: 30 },
  { name: 'Latte / Cappuccino', category: 'Coffee', caffeine: 64, size: 240 },
  { name: 'Decaf Coffee', category: 'Coffee', caffeine: 7, size: 240 },
  { name: 'Cold Brew', category: 'Coffee', caffeine: 200, size: 355 },
  { name: 'Instant Coffee', category: 'Coffee', caffeine: 62, size: 240 },
  { name: 'Iced Coffee', category: 'Coffee', caffeine: 165, size: 355 },
  { name: 'Americano', category: 'Coffee', caffeine: 154, size: 355 },
  { name: 'Mocha', category: 'Coffee', caffeine: 80, size: 355 },
  { name: 'Macchiato', category: 'Coffee', caffeine: 64, size: 60 },
  { name: 'Flat White', category: 'Coffee', caffeine: 130, size: 180 },
  { name: 'Nitro Cold Brew', category: 'Coffee', caffeine: 280, size: 355 },

  // Tea
  { name: 'Black Tea', category: 'Tea', caffeine: 47, size: 240 },
  { name: 'Green Tea', category: 'Tea', caffeine: 28, size: 240 },
  { name: 'White Tea', category: 'Tea', caffeine: 15, size: 240 },
  { name: 'Oolong Tea', category: 'Tea', caffeine: 37, size: 240 },
  { name: 'Matcha Tea', category: 'Tea', caffeine: 70, size: 240 },
  { name: 'Iced Tea (Black)', category: 'Tea', caffeine: 25, size: 355 },
  { name: 'Chai Tea Latte', category: 'Tea', caffeine: 95, size: 355 },
  { name: 'Herbal Tea', category: 'Tea', caffeine: 0, size: 240 },

  // Soda
  { name: 'Cola (Generic)', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Classic', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Diet Coke', category: 'Soda', caffeine: 46, size: 355 },
  { name: 'Coke Zero', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Pepsi', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'Diet Pepsi', category: 'Soda', caffeine: 36, size: 355 },
  { name: 'Dr Pepper', category: 'Soda', caffeine: 41, size: 355 },
  { name: 'Diet Dr Pepper', category: 'Soda', caffeine: 41, size: 355 },
  { name: 'Mountain Dew', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Diet Mountain Dew', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Sprite', category: 'Soda', caffeine: 0, size: 355 },
  { name: '7 Up', category: 'Soda', caffeine: 0, size: 355 },
  { name: 'Sunkist Orange', category: 'Soda', caffeine: 41, size: 355 },
  { name: 'A&W Cream Soda', category: 'Soda', caffeine: 29, size: 355 },
  { name: 'Barq\'s Root Beer', category: 'Soda', caffeine: 22, size: 355 },

  // Energy Drinks
  { name: 'Energy Drink (Generic)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Energy Shot (Generic)', category: 'Energy Drink', caffeine: 200, size: 60 },
  { name: 'Red Bull (250ml)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Red Bull (355ml)', category: 'Energy Drink', caffeine: 114, size: 355 },
  { name: 'Red Bull Sugarfree (250ml)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Monster Energy (473ml)', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Lo-Carb (473ml)', category: 'Energy Drink', caffeine: 140, size: 473 },
  { name: 'Monster Zero Ultra (473ml)', category: 'Energy Drink', caffeine: 140, size: 473 },
  { name: 'Rockstar (473ml)', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rockstar Sugar Free (473ml)', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Bang Energy (473ml)', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: '5-Hour Energy', category: 'Energy Drink', caffeine: 200, size: 57 },
  { name: '5-Hour Energy Extra Strength', category: 'Energy Drink', caffeine: 230, size: 57 },
  { name: 'Celsius (355ml)', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Reign Total Body Fuel (473ml)', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'VPX Bang', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Caffe Monster Energy Coffee', category: 'Coffee', caffeine: 175, size: 405 },
  { name: 'Monster Cuba Lima', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster DUB', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Export (UK)', category: 'Energy Drink', caffeine: 76, size: 250 },
  { name: 'Monster Hammer X-presso', category: 'Coffee', caffeine: 221, size: 200 },
  { name: 'Monster Heavy Metal', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Hitman Sniper', category: 'Energy Drink', caffeine: 240, size: 89 },
  { name: 'Monster Khaos', category: 'Energy Drink', caffeine: 154, size: 473 },
  { name: 'Monster M3 Energy Drink', category: 'Energy Drink', caffeine: 160, size: 148 },
  { name: 'Monster Maxx', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Monster Mixxd Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Mutant Super Soda', category: 'Soda', caffeine: 115, size: 591 },
  { name: 'Monster Rehab Green Tea', category: 'Tea', caffeine: 155, size: 458 },
  { name: 'Monster Ultra Pink', category: 'Energy Drink', caffeine: 140, size: 473 },
  { name: 'Monster Unleaded', category: 'Energy Drink', caffeine: 0, size: 473 },
  { name: 'Monster X-presso Hammer (NZ/AUS)', category: 'Coffee', caffeine: 90, size: 284 },
  { name: 'Ubermonster Energy Brew', category: 'Energy Drink', caffeine: 187, size: 550 },

  // Starbucks
  { name: 'Starbucks Brewed Coffee (Grande)', category: 'Coffee', caffeine: 310, size: 473 },
  { name: 'Starbucks Blonde Roast (Grande)', category: 'Coffee', caffeine: 360, size: 473 },
  { name: 'Starbucks Pike Place (Grande)', category: 'Coffee', caffeine: 310, size: 473 },
  { name: 'Starbucks Decaf Pike Place (Grande)', category: 'Coffee', caffeine: 25, size: 473 },
  { name: 'Starbucks Espresso Shot', category: 'Coffee', caffeine: 75, size: 22 },
  { name: 'Starbucks Caffe Latte (Grande)', category: 'Coffee', caffeine: 150, size: 473 },
  { name: 'Starbucks Cappuccino (Grande)', category: 'Coffee', caffeine: 150, size: 473 },
  { name: 'Starbucks Caffe Americano (Grande)', category: 'Coffee', caffeine: 225, size: 473 },
  { name: 'Starbucks Flat White (Grande)', category: 'Coffee', caffeine: 195, size: 473 },
  { name: 'Starbucks Caffe Mocha (Grande)', category: 'Coffee', caffeine: 175, size: 473 },
  { name: 'Starbucks Iced Coffee (Grande)', category: 'Coffee', caffeine: 165, size: 473 },
  { name: 'Starbucks Cold Brew (Grande)', category: 'Coffee', caffeine: 205, size: 473 },
  { name: 'Starbucks Nitro Cold Brew (Grande)', category: 'Coffee', caffeine: 280, size: 473 },
  { name: 'Starbucks Doubleshot on Ice', category: 'Coffee', caffeine: 150, size: 236 },
  { name: 'Starbucks Frappuccino Coffee (Grande)', category: 'Coffee', caffeine: 95, size: 473 },
  { name: 'Starbucks Iced Shaken Espresso (Grande)', category: 'Coffee', caffeine: 225, size: 473 },
  { name: 'Starbucks Chai Tea Latte (Grande)', category: 'Tea', caffeine: 95, size: 473 },
  { name: 'Starbucks Matcha Tea Latte (Grande)', category: 'Tea', caffeine: 80, size: 473 },
  { name: 'Starbucks Black Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473 },
  { name: 'Starbucks Green Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473 },
  { name: 'Starbucks Refresher (Grande)', category: 'Energy Drink', caffeine: 45, size: 473 },

  // Dunkin'
  { name: 'Dunkin\' Brewed Coffee (Medium)', category: 'Coffee', caffeine: 210, size: 414 },
  { name: 'Dunkin\' Decaf Coffee (Medium)', category: 'Coffee', caffeine: 10, size: 414 },
  { name: 'Dunkin\' Americano (Medium)', category: 'Coffee', caffeine: 284, size: 414 },
  { name: 'Dunkin\' Latte (Medium)', category: 'Coffee', caffeine: 166, size: 414 },
  { name: 'Dunkin\' Cappuccino (Medium)', category: 'Coffee', caffeine: 166, size: 414 },
  { name: 'Dunkin\' Espresso Shot', category: 'Coffee', caffeine: 98, size: 30 },
  { name: 'Dunkin\' Iced Coffee (Medium)', category: 'Coffee', caffeine: 297, size: 710 },
  { name: 'Dunkin\' Cold Brew (Medium)', category: 'Coffee', caffeine: 260, size: 710 },
  { name: 'Dunkin\' Frozen Coffee (Medium)', category: 'Coffee', caffeine: 295, size: 710 },
  { name: 'Dunkin\' Macchiato (Medium)', category: 'Coffee', caffeine: 284, size: 414 },
  { name: 'Dunkin\' Chai Latte (Medium)', category: 'Tea', caffeine: 108, size: 414 },

  // McDonald's
  { name: 'McDonald\'s McCafé Coffee (Medium)', category: 'Coffee', caffeine: 145, size: 473 },
  { name: 'McDonald\'s Iced Coffee (Medium)', category: 'Coffee', caffeine: 133, size: 473 },
  { name: 'McDonald\'s Latte (Medium)', category: 'Coffee', caffeine: 142, size: 473 },
  { name: 'McDonald\'s Americano (Medium)', category: 'Coffee', caffeine: 114, size: 473 },
  { name: 'McDonald\'s Espresso Shot', category: 'Coffee', caffeine: 71, size: 30 },
  { name: 'McDonald\'s Frappé (Medium)', category: 'Coffee', caffeine: 130, size: 473 },
  { name: 'McDonald\'s Sweet Tea (Medium)', category: 'Tea', caffeine: 100, size: 621 },

  // Other
  { name: 'Dark Chocolate (1 oz / 28g)', category: 'Other', caffeine: 24, size: 28 },
  { name: 'Milk Chocolate (1 oz / 28g)', category: 'Other', caffeine: 6, size: 28 },
  { name: 'Hot Chocolate (240ml)', category: 'Other', caffeine: 5, size: 240 },
  { name: 'Caffeine Pill', category: 'Other', caffeine: 200, size: 1 },
  { name: 'Pre-Workout Supplement (1 scoop)', category: 'Other', caffeine: 150, size: 10 },
  { name: 'NoDoz Max Strength', category: 'Other', caffeine: 200, size: 1 },
  { name: 'Excedrin Migraine (2 tablets)', category: 'Other', caffeine: 130, size: 2 },
  { name: 'Guayaki Yerba Mate (458ml can)', category: 'Tea', caffeine: 150, size: 458 },
  { name: 'Kombucha (240ml)', category: 'Tea', caffeine: 15, size: 240 },
  { name: 'Caffeinated Water (e.g., Water Joe)', category: 'Other', caffeine: 70, size: 500 },
  { name: 'Clif Shot Energy Gel (with caffeine)', category: 'Other', caffeine: 50, size: 34 },
  
  // New Additions
  { name: '28 Black Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: '3 Water', category: 'Other', caffeine: 50, size: 500 },
  { name: '3D Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: '4 Purpose Energy Drink', category: 'Energy Drink', caffeine: 70, size: 250 },
  { name: '4C Energy Drink Mix', category: 'Energy Drink', caffeine: 170, size: 500 },
  { name: '7 Eleven Brewed Coffee', category: 'Coffee', caffeine: 280, size: 473 },
  { name: '7-Eleven Energy Shot', category: 'Energy Drink', caffeine: 260, size: 59 },
  { name: 'A Shoc', category: 'Energy Drink', caffeine: 250, size: 473 },
  { name: 'ABB Turbo Tea Zero', category: 'Tea', caffeine: 120, size: 532 },
  { name: 'Accelerator', category: 'Energy Drink', caffeine: 150, size: 355 },
  { name: 'Advocare Slam Energy Shot', category: 'Energy Drink', caffeine: 120, size: 59 },
  { name: 'Advocare Slim', category: 'Energy Drink', caffeine: 120, size: 237 },
  { name: 'Afri Cola', category: 'Soda', caffeine: 83, size: 330 },
  { name: 'AHA Sparkling Water', category: 'Other', caffeine: 30, size: 355 },
  { name: 'Alani Nu Energy Drink', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Ale 8 1', category: 'Soda', caffeine: 37, size: 355 },
  { name: 'ALL IN Energy Drink', category: 'Energy Drink', caffeine: 75, size: 355 },
  { name: 'Alpine Start Instant Coffee', category: 'Coffee', caffeine: 120, size: 237 },
  { name: 'Alsa Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 473 },
  { name: 'AMIN.O. Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Amino Force Energy Drink', category: 'Energy Drink', caffeine: 200, size: 651 },
  { name: 'Arbonne Energy Fizz Stck', category: 'Energy Drink', caffeine: 55, size: 237 },
  { name: 'Arby\'s Jamocha Shake', category: 'Coffee', caffeine: 12, size: 473 },
  { name: 'Arizona Arnold Palmer Half and Half', category: 'Tea', caffeine: 15, size: 500 },
  { name: 'Arizona Energy Drink Rx', category: 'Energy Drink', caffeine: 127, size: 340 },
  { name: 'Arizona Iced Tea', category: 'Tea', caffeine: 30, size: 473 },
  { name: 'Arti Sparkling Water', category: 'Other', caffeine: 120, size: 355 },
  { name: 'AXIO Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Bai Antioxidant Infusion', category: 'Other', caffeine: 55, size: 532 },
  { name: 'Bai Boost', category: 'Energy Drink', caffeine: 110, size: 340 },
  { name: 'Balance Active Shot', category: 'Energy Drink', caffeine: 100, size: 59 },
  { name: 'Balance Energy Shot', category: 'Energy Drink', caffeine: 150, size: 59 },
  { name: 'Bang Keto Coffee', category: 'Coffee', caffeine: 300, size: 473 },
  { name: 'Bang Natural', category: 'Energy Drink', caffeine: 250, size: 473 },
  { name: 'Bang Shot', category: 'Energy Drink', caffeine: 300, size: 89 },
  { name: 'Bang Sweet Tea', category: 'Tea', caffeine: 300, size: 473 },
  { name: 'Barista Bros Iced Coffee', category: 'Coffee', caffeine: 140, size: 500 },
  { name: 'Baskin Robbins Cappuccino Blast', category: 'Coffee', caffeine: 234, size: 710 },
  { name: 'Bawls', category: 'Energy Drink', caffeine: 102, size: 473 },
  { name: 'BE Beyond Energy Drink', category: 'Energy Drink', caffeine: 160, size: 355 },
  { name: 'Beaver Buzz Energy Drink', category: 'Energy Drink', caffeine: 178, size: 473 },
  { name: 'BEEBAD Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Berocca', category: 'Other', caffeine: 90, size: 237 },
  { name: 'Berzerk Energy Drink Mix', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'Best Choice Strawberry Energy Drink Mix', category: 'Energy Drink', caffeine: 120, size: 237 },
  { name: 'Big Red Soda', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Big Train Java Chip Ice Coffee', category: 'Coffee', caffeine: 49, size: 355 },
  { name: 'Big Train Spiced Chai', category: 'Tea', caffeine: 65, size: 237 },
  { name: 'Bigelow Tea', category: 'Tea', caffeine: 45, size: 237 },
  { name: 'Biggby Brewed Coffee', category: 'Coffee', caffeine: 200, size: 473 },
  { name: 'Biggby Creamy Lattes', category: 'Coffee', caffeine: 100, size: 473 },
  { name: 'Biggby Espresso', category: 'Coffee', caffeine: 100, size: 59 },
  { name: 'Biggby Iced Coffee', category: 'Coffee', caffeine: 155, size: 473 },
  { name: 'Biggby Iced Tea', category: 'Tea', caffeine: 38, size: 473 },
  { name: 'Bing Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Bizzy Cold Brew', category: 'Coffee', caffeine: 125, size: 79 },
  { name: 'Black Bruin Energy Drink', category: 'Energy Drink', caffeine: 38, size: 250 },
  { name: 'Black Ink Coffee', category: 'Coffee', caffeine: 144, size: 355 },
  { name: 'Black Insomnia Coffee', category: 'Coffee', caffeine: 1105, size: 355 },
  { name: 'Black Label Brewed Coffee', category: 'Coffee', caffeine: 1555, size: 355 },
  { name: 'Bloom Energy', category: 'Energy Drink', caffeine: 180, size: 355 },
  { name: 'Blu Frog Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Blue Bolt (UK)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Blue Charge (UK)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Blue Spark (UK)', category: 'Energy Drink', caffeine: 75, size: 250 },
  { name: 'Bodyarmour Edge', category: 'Energy Drink', caffeine: 100, size: 591 },
  { name: 'Bomb Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Bomba (EU)', category: 'Energy Drink', caffeine: 80, size: 248 },
  { name: 'Boost Energy (UK)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Boost Nutritional Drink', category: 'Other', caffeine: 5, size: 237 },
  { name: 'Bottled Iced Coffee Dunkin Donuts', category: 'Coffee', caffeine: 197, size: 405 },
  { name: 'BPM Energy Drink', category: 'Energy Drink', caffeine: 70, size: 500 },
  { name: 'BreinFuel', category: 'Energy Drink', caffeine: 360, size: 355 },
  { name: 'Brew Dr Kombucha Uplift', category: 'Tea', caffeine: 130, size: 414 },
  { name: 'Brisk Iced Tea', category: 'Tea', caffeine: 11, size: 355 },
  { name: 'Brown Rice Tea', category: 'Tea', caffeine: 4, size: 237 },
  { name: 'Bubbl\'r Sparkling Water', category: 'Other', caffeine: 69, size: 355 },
  { name: 'Bubly Bounce Sparkling Water', category: 'Other', caffeine: 35, size: 355 },
  { name: 'Bubly Sparkling Water', category: 'Other', caffeine: 0, size: 355 },
  { name: 'Bucked Up', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Bulletproof Coffee', category: 'Coffee', caffeine: 145, size: 237 },
  { name: 'Burn Energy Drink', category: 'Energy Drink', caffeine: 112, size: 355 },
  { name: 'C4 On The Go', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'C4 Performance Energy', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'C4 Smart Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'C4 Ultimate Energy Drink', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Cafe Bustelo', category: 'Coffee', caffeine: 150, size: 355 },
  { name: 'Cafe Con Leche', category: 'Coffee', caffeine: 154, size: 177 },
  { name: 'Caffe Mocha', category: 'Coffee', caffeine: 152, size: 355 },
  { name: 'Caffe Nero Coffee', category: 'Coffee', caffeine: 160, size: 355 },
  { name: 'Califia Farms Cold Brew Coffee', category: 'Coffee', caffeine: 180, size: 237 },
  { name: 'Canada Dry Green Tea Ginger Ale', category: 'Soda', caffeine: 9, size: 355 },
  { name: 'Cannonball Coffee Maximum Charge (UK)', category: 'Coffee', caffeine: 1101, size: 355 },
  { name: 'Carabao Energy Drink (UK)', category: 'Energy Drink', caffeine: 106, size: 330 },
  { name: 'Caribou BOUsted Sparkling Water', category: 'Other', caffeine: 75, size: 340 },
  { name: 'Caribou Brewed Coffee', category: 'Coffee', caffeine: 305, size: 473 },
  { name: 'Caribou Canned Cold Brew', category: 'Coffee', caffeine: 177, size: 340 },
  { name: 'Cascara', category: 'Tea', caffeine: 36, size: 237 },
  { name: 'CBD Coffee', category: 'Coffee', caffeine: 100, size: 237 },
  { name: 'Celsius Stevia', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Chai Tea', category: 'Tea', caffeine: 50, size: 237 },
  { name: 'Chameleon Cold Brew Coffee', category: 'Coffee', caffeine: 210, size: 237 },
  { name: 'Chameleon Cold Brew RTD', category: 'Coffee', caffeine: 230, size: 296 },
  { name: 'Chameleon Cold Brew With Milk', category: 'Coffee', caffeine: 100, size: 325 },
  { name: 'Cheerwine', category: 'Soda', caffeine: 47, size: 355 },
  { name: 'Chick-fil-A Brewed Coffee', category: 'Coffee', caffeine: 136, size: 296 },
  { name: 'Chick-fil-A Frosted Coffee', category: 'Coffee', caffeine: 130, size: 414 },
  { name: 'Chick-fil-A Iced Coffee', category: 'Coffee', caffeine: 80, size: 414 },
  { name: 'Chick-fil-A Iced Tea', category: 'Tea', caffeine: 62, size: 473 },
  { name: 'Choffy (roasted cacao)', category: 'Other', caffeine: 23, size: 177 },
  { name: 'Cintron Energy Drink', category: 'Energy Drink', caffeine: 85, size: 248 },
  { name: 'Club Mate (EU)', category: 'Energy Drink', caffeine: 100, size: 500 },
  { name: 'Coca Cola Plus', category: 'Soda', caffeine: 45, size: 470 },
  { name: 'Coca-Cola Caffeine Free', category: 'Soda', caffeine: 0, size: 355 },
  { name: 'Coca-Cola Cherry', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Cherry Vanilla', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Cherry Zero Sugar', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Energy', category: 'Energy Drink', caffeine: 114, size: 355 },
  { name: 'Coca-Cola Orange Vanilla', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Vanilla', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola Vanilla Zero Sugar', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Coca-Cola With Coffee', category: 'Coffee', caffeine: 69, size: 355 },
  { name: 'Coca-Cola Zero Sugar', category: 'Soda', caffeine: 34, size: 355 },
  { name: 'Cocaine Energy Drink', category: 'Energy Drink', caffeine: 280, size: 355 },
  { name: 'Coffee (Generic)', category: 'Coffee', caffeine: 163, size: 237 },
  { name: 'Coffee (Decaf, Instant)', category: 'Coffee', caffeine: 2, size: 237 },
  { name: 'Coffee (Moka Pot)', category: 'Coffee', caffeine: 93, size: 59 },
  { name: 'Coffee Bean & Tea leaf Coffee', category: 'Coffee', caffeine: 333, size: 473 },
  { name: 'Coffee Friend Brewed Coffee', category: 'Coffee', caffeine: 145, size: 250 },
  { name: 'Coffee Leaf Tea', category: 'Tea', caffeine: 20, size: 237 },
  { name: 'COGO Caffeinated Hot Chocolate', category: 'Other', caffeine: 98, size: 177 },
  { name: 'Cold Brew Tea', category: 'Tea', caffeine: 70, size: 237 },
  { name: 'CoolBrew Coffee', category: 'Coffee', caffeine: 60, size: 296 },
  { name: 'Costa Coffee', category: 'Coffee', caffeine: 241, size: 300 },
  { name: 'Cran Energy Juice', category: 'Energy Drink', caffeine: 70, size: 296 },
  { name: 'Crave Energy Drink (UK)', category: 'Energy Drink', caffeine: 80, size: 249 },
  { name: 'Crio Bru Brewed Cacao', category: 'Other', caffeine: 10, size: 237 },
  { name: 'Crunk Energy Drink', category: 'Energy Drink', caffeine: 192, size: 473 },
  { name: 'Crystal Light Energy Mix', category: 'Energy Drink', caffeine: 60, size: 473 },
  { name: 'Crystal Light Iced Tea', category: 'Tea', caffeine: 10, size: 237 },
  { name: 'Dare Iced Coffee', category: 'Coffee', caffeine: 160, size: 500 },
  { name: 'Dark Dog Organic Energy', category: 'Energy Drink', caffeine: 114, size: 355 },
  { name: 'Death Wish Canned Cold Brew', category: 'Coffee', caffeine: 300, size: 237 },
  { name: 'Death Wish Coffee', category: 'Coffee', caffeine: 728, size: 355 },
  { name: 'Death Wish Latte', category: 'Coffee', caffeine: 300, size: 237 },
  { name: 'Demon Energy Drink', category: 'Energy Drink', caffeine: 160, size: 500 },
  { name: 'Diet Wild Cherry Pepsi', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'doc Soda', category: 'Soda', caffeine: 60, size: 355 },
  { name: 'Double Cola', category: 'Soda', caffeine: 36, size: 355 },
  { name: 'Dr Pepper 10', category: 'Soda', caffeine: 51, size: 355 },
  { name: 'Dr Pepper Zero Sugar', category: 'Soda', caffeine: 41, size: 355 },
  { name: 'Dr Shasta Soda', category: 'Soda', caffeine: 29, size: 355 },
  { name: 'Driftaway Coffee', category: 'Coffee', caffeine: 160, size: 237 },
  { name: 'Dripdash Kyoto Coffee', category: 'Coffee', caffeine: 225, size: 177 },
  { name: 'Duff Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Dunkin Donuts Shot In The Dark', category: 'Coffee', caffeine: 134, size: 240 },
  { name: 'Dunkin Sparkd Energy', category: 'Energy Drink', caffeine: 192, size: 946 },
  { name: 'Dunkin\' Donuts Dunkaccino', category: 'Coffee', caffeine: 83, size: 414 },
  { name: 'Dunkin\' Donuts Extra Charged Coffee', category: 'Coffee', caffeine: 252, size: 414 },
  { name: 'Dunkin\' Donuts Iced Tea', category: 'Tea', caffeine: 63, size: 710 },
  { name: 'Dutch Bros Blue Rebel Energy Drink', category: 'Energy Drink', caffeine: 80, size: 248 },
  { name: 'Dutch Bros Coffee (Classic)', category: 'Coffee', caffeine: 187, size: 591 },
  { name: 'DynaPep', category: 'Energy Drink', caffeine: 100, size: 4 },
  { name: 'E6 Energy Shot', category: 'Energy Drink', caffeine: 235, size: 57 },
  { name: 'EBOOST Energy Drink Mix', category: 'Energy Drink', caffeine: 110, size: 237 },
  { name: 'EBOOST Super Fuel', category: 'Energy Drink', caffeine: 110, size: 355 },
  { name: 'EBOOST Workout Crusher Mix', category: 'Energy Drink', caffeine: 175, size: 237 },
  { name: 'Eight O\'Clock Coffee', category: 'Coffee', caffeine: 112, size: 237 },
  { name: 'Einstein Bros Coffee', category: 'Coffee', caffeine: 206, size: 473 },
  { name: 'Electric Monkey Wild Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'EnerBee Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Equip Pure Energy Shot', category: 'Energy Drink', caffeine: 100, size: 53 },
  { name: 'Espresso Monster', category: 'Coffee', caffeine: 160, size: 248 },
  { name: 'Eternal Energy Extra Strength', category: 'Energy Drink', caffeine: 280, size: 57 },
  { name: 'Eternal Energy Shot', category: 'Energy Drink', caffeine: 230, size: 57 },
  { name: 'Euro Shopper Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'F3 Energy', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Fakeer Energy Drink (EU)', category: 'Energy Drink', caffeine: 118, size: 370 },
  { name: 'Fast Lane Black Tea', category: 'Tea', caffeine: 110, size: 237 },
  { name: 'Faxe Kondi', category: 'Soda', caffeine: 26, size: 330 },
  { name: 'Faygo Cola', category: 'Soda', caffeine: 43, size: 355 },
  { name: 'Faygo Moon Mist', category: 'Soda', caffeine: 20, size: 355 },
  { name: 'Folgers Coffee', category: 'Coffee', caffeine: 112, size: 237 },
  { name: 'Forto Organic Coffee Shot', category: 'Coffee', caffeine: 225, size: 59 },
  { name: 'Freeway Cola', category: 'Soda', caffeine: 32, size: 330 },
  { name: 'Fritz Kola (EU)', category: 'Soda', caffeine: 83, size: 330 },
  { name: 'Full Throttle Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Fuze Iced Tea', category: 'Tea', caffeine: 24, size: 591 },
  { name: 'Gamer Supps GG Energy Mix', category: 'Energy Drink', caffeine: 100, size: 237 },
  { name: 'Gatorade Bolt 24 Energize', category: 'Energy Drink', caffeine: 75, size: 500 },
  { name: 'Gatorade Fast Twitch', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'GFuel Cans', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'GFuel Energy Drink Mix', category: 'Energy Drink', caffeine: 140, size: 473 },
  { name: 'Ghost Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'Gloria Jean\'s Coffee', category: 'Coffee', caffeine: 67, size: 60 },
  { name: 'Go Fast Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Go Fast High Octane Energy Drink', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Go Girl Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Goat Fuel', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Gold Peak Coffee', category: 'Coffee', caffeine: 126, size: 237 },
  { name: 'Gold Peak Tea', category: 'Tea', caffeine: 48, size: 547 },
  { name: 'Gothrider Gasoline Coffee', category: 'Coffee', caffeine: 200, size: 237 },
  { name: 'Gourmesso Coffee Pods', category: 'Coffee', caffeine: 65, size: 40 },
  { name: 'Great Value Energy Drink Enhancers', category: 'Energy Drink', caffeine: 50, size: 237 },
  { name: 'Great Value Energy Drink Mix', category: 'Energy Drink', caffeine: 120, size: 473 },
  { name: 'Greek Coffee (Metrios)', category: 'Coffee', caffeine: 50, size: 59 },
  { name: 'Green Cola', category: 'Soda', caffeine: 37, size: 355 },
  { name: 'Gridlock Energy Drink', category: 'Energy Drink', caffeine: 140, size: 473 },
  { name: 'Guayaki Yerba Mate Bottled Tea', category: 'Tea', caffeine: 140, size: 473 },
  { name: 'Guayusa Tea', category: 'Tea', caffeine: 41, size: 237 },
  { name: 'GURU Energy Drink', category: 'Energy Drink', caffeine: 140, size: 355 },
  { name: 'GURU Sparkling Energy Water', category: 'Other', caffeine: 100, size: 355 },
  { name: 'GymBrew Coffee', category: 'Coffee', caffeine: 333, size: 355 },
  { name: 'Half Caff Folgers', category: 'Coffee', caffeine: 58, size: 177 },
  { name: 'Hell Energy Coffee', category: 'Coffee', caffeine: 100, size: 250 },
  { name: 'Hell Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Heroec Energy Water', category: 'Other', caffeine: 60, size: 500 },
  { name: 'Hi Ball Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'HICAF Tea', category: 'Tea', caffeine: 110, size: 237 },
  { name: 'High Brew Coffee', category: 'Coffee', caffeine: 140, size: 237 },
  { name: 'High Voltage Coffee (AU)', category: 'Coffee', caffeine: 1150, size: 355 },
  { name: 'Hint Caffeine Kick Water', category: 'Other', caffeine: 60, size: 473 },
  { name: 'Honest Iced Tea', category: 'Tea', caffeine: 63, size: 500 },
  { name: 'Hot6 the King Energy', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Hyde Xtreme', category: 'Energy Drink', caffeine: 400, size: 355 },
  { name: 'Hype Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Illy Issimo Cafe', category: 'Coffee', caffeine: 155, size: 201 },
  { name: 'Inca Kola', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'Indulgio Cappuccino', category: 'Coffee', caffeine: 20, size: 237 },
  { name: 'Inko\'s White Tea Energy', category: 'Tea', caffeine: 165, size: 458 },
  { name: 'International Delight Iced Coffee', category: 'Coffee', caffeine: 88, size: 355 },
  { name: 'Irn Bru (UK)', category: 'Soda', caffeine: 30, size: 330 },
  { name: 'Java Kick Coffee Cola', category: 'Soda', caffeine: 100, size: 355 },
  { name: 'Java Monster', category: 'Coffee', caffeine: 200, size: 444 },
  { name: 'Java Monster 300', category: 'Coffee', caffeine: 300, size: 444 },
  { name: 'Javvy Coffee Concentrate', category: 'Coffee', caffeine: 80, size: 177 },
  { name: 'Joker Mad Energy', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Jolt Cola', category: 'Soda', caffeine: 200, size: 473 },
  { name: 'Juice Monster', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Juvee', category: 'Energy Drink', caffeine: 128, size: 355 },
  { name: 'K Cup Decaf', category: 'Coffee', caffeine: 4, size: 237 },
  { name: 'K Cup Tea', category: 'Tea', caffeine: 41, size: 237 },
  { name: 'K-Cup Coffee', category: 'Coffee', caffeine: 100, size: 237 },
  { name: 'Kaffn8 Liquified Caffeine', category: 'Other', caffeine: 75, size: 7 },
  { name: 'Kickapoo Soda: Joy Juice & Fruit Shine', category: 'Soda', caffeine: 40, size: 355 },
  { name: 'Kill Cliff Energy X Recover', category: 'Energy Drink', caffeine: 25, size: 355 },
  { name: 'Kill Cliff Ignite', category: 'Energy Drink', caffeine: 150, size: 355 },
  { name: 'Killer Coffee (AU)', category: 'Coffee', caffeine: 430, size: 250 },
  { name: 'Kin Spritz', category: 'Other', caffeine: 50, size: 237 },
  { name: 'Kirkland Energy Shot', category: 'Energy Drink', caffeine: 180, size: 59 },
  { name: 'KOE Kombucha', category: 'Tea', caffeine: 15, size: 355 },
  { name: 'Kona Gold Energy Drink', category: 'Energy Drink', caffeine: 115, size: 355 },
  { name: 'La Colombe Draft Latte', category: 'Coffee', caffeine: 120, size: 266 },
  { name: 'LevlUp Gaming Booster', category: 'Energy Drink', caffeine: 250, size: 500 },
  { name: 'Limitless Sparkling Water', category: 'Other', caffeine: 35, size: 355 },
  { name: 'Lipton Iced Tea', category: 'Tea', caffeine: 25, size: 591 },
  { name: 'Lipton Natural Energy Tea', category: 'Tea', caffeine: 75, size: 237 },
  { name: 'Lipton Tea', category: 'Tea', caffeine: 55, size: 237 },
  { name: 'Liquid Death Iced Tea', category: 'Tea', caffeine: 30, size: 568 },
  { name: 'Liquid Help Energy Drink', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Liquid Ice Energy Drink', category: 'Energy Drink', caffeine: 80, size: 245 },
  { name: 'Liquid IV Energy', category: 'Energy Drink', caffeine: 100, size: 473 },
  { name: 'Live+ Energy Drink', category: 'Energy Drink', caffeine: 150, size: 500 },
  { name: 'Long Black', category: 'Coffee', caffeine: 154, size: 177 },
  { name: 'Lucozade', category: 'Soda', caffeine: 46, size: 380 },
  { name: 'LYFT Energy Mix', category: 'Energy Drink', caffeine: 125, size: 237 },
  { name: 'M-150 Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Mamma Chia Energy', category: 'Energy Drink', caffeine: 90, size: 296 },
  { name: 'Mana Energy Potion', category: 'Energy Drink', caffeine: 75, size: 50 },
  { name: 'Marquis Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Master Brew Kombucha', category: 'Tea', caffeine: 76, size: 450 },
  { name: 'MATI Energy Drink', category: 'Energy Drink', caffeine: 110, size: 355 },
  { name: 'Maxwell House Coffee', category: 'Coffee', caffeine: 112, size: 237 },
  { name: 'Maxwell House Max Boost Coffee', category: 'Coffee', caffeine: 196, size: 237 },
  { name: 'McDonalds (McCafe) Latte', category: 'Coffee', caffeine: 142, size: 473 },
  { name: 'McDonalds (McCafe) Mocha', category: 'Coffee', caffeine: 167, size: 473 },
  { name: 'McDonalds Coffee', category: 'Coffee', caffeine: 145, size: 473 },
  { name: 'McDonalds Iced Coffee', category: 'Coffee', caffeine: 133, size: 340 },
  { name: 'McDonalds Sweet Tea', category: 'Tea', caffeine: 100, size: 946 },
  { name: 'Mega Monster Energy Drink', category: 'Energy Drink', caffeine: 240, size: 710 },
  { name: 'Mello Yello', category: 'Soda', caffeine: 51, size: 355 },
  { name: 'Meltdown Ketone Drink', category: 'Energy Drink', caffeine: 225, size: 355 },
  { name: 'MiO Energy Water Enhancer', category: 'Energy Drink', caffeine: 60, size: 237 },
  { name: 'Monster Assault', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Dragon Tea', category: 'Tea', caffeine: 60, size: 680 },
  { name: 'Monster Hydro', category: 'Energy Drink', caffeine: 188, size: 751 },
  { name: 'Monster Import', category: 'Energy Drink', caffeine: 179, size: 550 },
  { name: 'Monster Killer Brew', category: 'Coffee', caffeine: 300, size: 444 },
  { name: 'Monster Mango Loco', category: 'Energy Drink', caffeine: 152, size: 473 },
  { name: 'Monster Mule', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Nitro', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Pipeline Punch', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Rehab', category: 'Tea', caffeine: 160, size: 458 },
  { name: 'Monster Reserve', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Monster Ripper Energy Juice (UK)', category: 'Energy Drink', caffeine: 160, size: 500 },
  { name: 'Monster The Doctor VR46 (UK)', category: 'Energy Drink', caffeine: 160, size: 500 },
  { name: 'Monster Tour Water', category: 'Other', caffeine: 0, size: 473 },
  { name: 'Monster Ultra', category: 'Energy Drink', caffeine: 150, size: 473 },
  { name: 'Monster Zero Sugar', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Moose Juice Energy Drink', category: 'Energy Drink', caffeine: 200, size: 501 },
  { name: 'Morning Thunder Tea', category: 'Tea', caffeine: 45, size: 237 },
  { name: 'Mother Energy Drink', category: 'Energy Drink', caffeine: 160, size: 500 },
  { name: 'Mount Hagen Instant Coffee', category: 'Coffee', caffeine: 70, size: 237 },
  { name: 'Mountain Dew Amp', category: 'Energy Drink', caffeine: 142, size: 473 },
  { name: 'Mountain Dew Baja Blast', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Mountain Dew Code Red', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Mountain Dew Energy', category: 'Energy Drink', caffeine: 180, size: 473 },
  { name: 'Mountain Dew Game Fuel', category: 'Energy Drink', caffeine: 90, size: 473 },
  { name: 'Mountain Dew Kickstart', category: 'Energy Drink', caffeine: 90, size: 473 },
  { name: 'Mountain Dew Live Wire', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Mountain Dew Major Melon', category: 'Soda', caffeine: 55, size: 355 },
  { name: 'Mountain Dew Spark', category: 'Soda', caffeine: 46, size: 355 },
  { name: 'Mountain Dew Voltage', category: 'Soda', caffeine: 55, size: 355 },
  { name: 'Mountain Dew Zero Sugar', category: 'Soda', caffeine: 68, size: 355 },
  { name: 'Moxie Soda', category: 'Soda', caffeine: 24, size: 355 },
  { name: 'Mucho Mango Energy Drink', category: 'Energy Drink', caffeine: 0, size: 237 },
  { name: 'Muscle Milk Coffee House', category: 'Coffee', caffeine: 120, size: 325 },
  { name: 'Muscle Monster', category: 'Energy Drink', caffeine: 157, size: 444 },
  { name: 'Mushroom Coffee', category: 'Coffee', caffeine: 50, size: 237 },
  { name: 'Nerd Focus', category: 'Energy Drink', caffeine: 128, size: 355 },
  { name: 'Nescafe 3 in 1 Instant Coffee', category: 'Coffee', caffeine: 50, size: 177 },
  { name: 'Nescafe Dolce Gusto', category: 'Coffee', caffeine: 106, size: 237 },
  { name: 'Nescafe Gold', category: 'Coffee', caffeine: 66, size: 250 },
  { name: 'Nescafe Ice Java', category: 'Coffee', caffeine: 100, size: 237 },
  { name: 'Nescafe Ricoffy', category: 'Coffee', caffeine: 6, size: 237 },
  { name: 'Nespresso Coffee Capsules', category: 'Coffee', caffeine: 60, size: 40 },
  { name: 'Nestea Iced Tea', category: 'Tea', caffeine: 23, size: 500 },
  { name: 'Nestle Milo', category: 'Other', caffeine: 4, size: 237 },
  { name: 'Neu Nootropic Shot', category: 'Energy Drink', caffeine: 350, size: 59 },
  { name: 'Neuro Sonic', category: 'Energy Drink', caffeine: 100, size: 430 },
  { name: 'NOCCO Energy Drink (EU)', category: 'Energy Drink', caffeine: 180, size: 330 },
  { name: 'Noocaf Smart Coffee', category: 'Coffee', caffeine: 160, size: 237 },
  { name: 'NOS Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Nutramint Smart Serum', category: 'Energy Drink', caffeine: 200, size: 59 },
  { name: 'Nuun Sport', category: 'Other', caffeine: 40, size: 473 },
  { name: 'OCA Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Ocean Spray Brew', category: 'Other', caffeine: 40, size: 237 },
  { name: 'Octane Energy Drink Mix', category: 'Energy Drink', caffeine: 225, size: 355 },
  { name: 'Oi Ocha Green Tea', category: 'Tea', caffeine: 60, size: 500 },
  { name: 'Oikos Pro Fuel', category: 'Other', caffeine: 100, size: 296 },
  { name: 'OK Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'OLIPOP Vintage Cola', category: 'Soda', caffeine: 50, size: 355 },
  { name: 'Oregon Chai Tea', category: 'Tea', caffeine: 45, size: 177 },
  { name: 'Pacific Chai', category: 'Tea', caffeine: 29, size: 177 },
  { name: 'Panera Bread Coffee', category: 'Coffee', caffeine: 189, size: 473 },
  { name: 'PC Cola', category: 'Soda', caffeine: 12, size: 355 },
  { name: 'PC Cola Diet', category: 'Soda', caffeine: 13, size: 355 },
  { name: 'Peace Tea', category: 'Tea', caffeine: 23, size: 680 },
  { name: 'Peet\'s Brewed Coffee', category: 'Coffee', caffeine: 267, size: 473 },
  { name: 'Peet\'s Caffe Americano', category: 'Coffee', caffeine: 140, size: 473 },
  { name: 'Peet\'s Caffe Latte', category: 'Coffee', caffeine: 140, size: 473 },
  { name: 'Peet\'s Caffe Mocha', category: 'Coffee', caffeine: 165, size: 473 },
  { name: 'Peet\'s Cappuccino', category: 'Coffee', caffeine: 140, size: 473 },
  { name: 'Peet\'s Coffee Espresso', category: 'Coffee', caffeine: 70, size: 44 },
  { name: 'Peet\'s Decaf Espresso', category: 'Coffee', caffeine: 10, size: 44 },
  { name: 'Peet\'s Iced Coffee', category: 'Coffee', caffeine: 150, size: 473 },
  { name: 'Peet\'s Iced Latte', category: 'Coffee', caffeine: 140, size: 473 },
  { name: 'Peet\'s Iced Mocha', category: 'Coffee', caffeine: 165, size: 473 },
  { name: 'Pep Talk Sparkling Water', category: 'Other', caffeine: 55, size: 355 },
  { name: 'Pepsi Caffeine Free', category: 'Soda', caffeine: 0, size: 355 },
  { name: 'Pepsi Made With Sugar', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'Pepsi Max (UK)', category: 'Soda', caffeine: 43, size: 330 },
  { name: 'Pepsi Zero Sugar', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'Performance Caffeine', category: 'Other', caffeine: 180, size: 59 },
  { name: 'PerformElite Pre-Workout', category: 'Energy Drink', caffeine: 225, size: 237 },
  { name: 'Perk Energy Beverage', category: 'Energy Drink', caffeine: 100, size: 237 },
  { name: 'Perrier Energize', category: 'Other', caffeine: 99, size: 250 },
  { name: 'PG Tips Black Tea', category: 'Tea', caffeine: 50, size: 201 },
  { name: 'Phocus Sparkling Water', category: 'Other', caffeine: 75, size: 340 },
  { name: 'Phoenix Energy Shot', category: 'Energy Drink', caffeine: 280, size: 59 },
  { name: 'Pibb Xtra', category: 'Soda', caffeine: 40, size: 355 },
  { name: 'Poland Spring Sparkling Energy Water', category: 'Other', caffeine: 75, size: 340 },
  { name: 'Polar Frost Plus Energy', category: 'Other', caffeine: 67, size: 503 },
  { name: 'Poppi Soda Classic Cola', category: 'Soda', caffeine: 32, size: 355 },
  { name: 'Power Horse Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Premier Protein Cafe Latte', category: 'Coffee', caffeine: 120, size: 340 },
  { name: 'Premium Cola (EU)', category: 'Soda', caffeine: 83, size: 330 },
  { name: 'Prime Energy Drink', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Private Selection Canned Espresso', category: 'Coffee', caffeine: 145, size: 444 },
  { name: 'Proper Wild Energy Shot', category: 'Energy Drink', caffeine: 180, size: 74 },
  { name: 'Protein2O + Energy', category: 'Energy Drink', caffeine: 125, size: 500 },
  { name: 'Pure Boost Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 473 },
  { name: 'Pure Cofain 699 (EU)', category: 'Energy Drink', caffeine: 175, size: 250 },
  { name: 'Pure Kick Energy Drink Mix', category: 'Energy Drink', caffeine: 80, size: 500 },
  { name: 'Pure Leaf Iced Tea', category: 'Tea', caffeine: 69, size: 547 },
  { name: 'Purity Coffee', category: 'Coffee', caffeine: 163, size: 237 },
  { name: 'Quake Energy Berry Blast Slurpee', category: 'Energy Drink', caffeine: 92, size: 473 },
  { name: 'Quake Energy Drink', category: 'Energy Drink', caffeine: 250, size: 473 },
  { name: 'Rambler Energy Drink', category: 'Energy Drink', caffeine: 120, size: 473 },
  { name: 'Raze Energy Drink', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'RC (Royal Crown) Cola', category: 'Soda', caffeine: 43, size: 355 },
  { name: 'Red Bull Editions', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Red Bull Simply Cola', category: 'Soda', caffeine: 32, size: 250 },
  { name: 'Red Bull Zero', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Red Devil Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Red Eye Energy Drink', category: 'Energy Drink', caffeine: 106, size: 328 },
  { name: 'Red Power Elixir', category: 'Energy Drink', caffeine: 160, size: 355 },
  { name: 'Red Thunder Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Red Thunder Energy Shot', category: 'Energy Drink', caffeine: 138, size: 59 },
  { name: 'Red Thunder Extra Strength', category: 'Energy Drink', caffeine: 230, size: 59 },
  { name: 'Redline Max 300', category: 'Energy Drink', caffeine: 300, size: 74 },
  { name: 'Redline Princess', category: 'Energy Drink', caffeine: 300, size: 237 },
  { name: 'Redline Xtreme Energy Drink', category: 'Energy Drink', caffeine: 316, size: 237 },
  { name: 'Redline Xtreme Shot', category: 'Energy Drink', caffeine: 300, size: 89 },
  { name: 'Reed\'s Ginger Energize Shot', category: 'Other', caffeine: 100, size: 59 },
  { name: 'Reign Storm', category: 'Energy Drink', caffeine: 200, size: 355 },
  { name: 'Revv Coffee Pods', category: 'Coffee', caffeine: 127, size: 237 },
  { name: 'Riot Energy', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rip It Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rip It Energy Shot', category: 'Energy Drink', caffeine: 120, size: 59 },
  { name: 'Rise Nitro Cold Brew Coffee', category: 'Coffee', caffeine: 250, size: 296 },
  { name: 'Ritz Cola', category: 'Soda', caffeine: 10, size: 355 },
  { name: 'Roaring Lion Energy Drink', category: 'Energy Drink', caffeine: 77, size: 237 },
  { name: 'Robusta Coffee', category: 'Coffee', caffeine: 265, size: 237 },
  { name: 'Rockstar Boom', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rockstar Energy Drink (Original)', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rockstar Halo Infinite', category: 'Energy Drink', caffeine: 240, size: 473 },
  { name: 'Rockstar Juiced', category: 'Energy Drink', caffeine: 170, size: 473 },
  { name: 'Rockstar Organic Energy Drink', category: 'Energy Drink', caffeine: 160, size: 444 },
  { name: 'Rockstar Punched', category: 'Energy Drink', caffeine: 240, size: 473 },
  { name: 'Rockstar Pure Zero', category: 'Energy Drink', caffeine: 240, size: 473 },
  { name: 'Rockstar Recovery', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Rockstar Thermo', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Rockstar Unplugged', category: 'Energy Drink', caffeine: 80, size: 237 },
  { name: 'Rockstar XDurance', category: 'Energy Drink', caffeine: 300, size: 473 },
  { name: 'Rockstar Zero Carb', category: 'Energy Drink', caffeine: 240, size: 473 },
  { name: 'Rogue Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'Rogue Energy Drink Mix', category: 'Energy Drink', caffeine: 175, size: 473 },
  { name: 'RootJack Caffeinated Pirate Root Beer', category: 'Soda', caffeine: 120, size: 355 },
  { name: 'Rowdy Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Ruby Red Squirt', category: 'Soda', caffeine: 39, size: 355 },
  { name: 'Runa', category: 'Energy Drink', caffeine: 150, size: 355 },
  { name: 'Rush! Energy Drink', category: 'Energy Drink', caffeine: 80, size: 245 },
  { name: 'Ryse Fuel', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'Sambazon Amazon Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'Scheckters Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Score Energy Drink Gorilla', category: 'Energy Drink', caffeine: 150, size: 500 },
  { name: 'Screamin Energy Max Hit', category: 'Energy Drink', caffeine: 185, size: 18 },
  { name: 'Seattle\'s Best Brewed Coffee', category: 'Coffee', caffeine: 260, size: 355 },
  { name: 'Sencha Green Tea Shot', category: 'Tea', caffeine: 40, size: 189 },
  { name: 'Shasta Cola', category: 'Soda', caffeine: 43, size: 355 },
  { name: 'Shasta Diet Cola', category: 'Soda', caffeine: 47, size: 355 },
  { name: 'Shasta Mountain Rush', category: 'Soda', caffeine: 54, size: 355 },
  { name: 'Ski Soda', category: 'Soda', caffeine: 69, size: 355 },
  { name: 'Slammers Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'SlimFast Shake - Cappuccino', category: 'Coffee', caffeine: 100, size: 325 },
  { name: 'Slurpee', category: 'Soda', caffeine: 30, size: 355 },
  { name: 'Snapple Tea', category: 'Tea', caffeine: 37, size: 473 },
  { name: 'Sneak Energy Drink Mix', category: 'Energy Drink', caffeine: 150, size: 473 },
  { name: 'SoBe Energy Citrus', category: 'Energy Drink', caffeine: 81, size: 591 },
  { name: 'SoBe Green Tea', category: 'Tea', caffeine: 7, size: 591 },
  { name: 'Soda Stream', category: 'Soda', caffeine: 31, size: 237 },
  { name: 'Solimo Energy Drink', category: 'Energy Drink', caffeine: 152, size: 473 },
  { name: 'Source 1899 (UK)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Southern Sweet Tea', category: 'Tea', caffeine: 41, size: 473 },
  { name: 'Soylent Stacked', category: 'Other', caffeine: 100, size: 330 },
  { name: 'Spark Energy Drink Mix', category: 'Energy Drink', caffeine: 120, size: 237 },
  { name: 'Sparkling Ice Caffeine', category: 'Other', caffeine: 70, size: 473 },
  { name: 'Sparkling Ice Energy', category: 'Energy Drink', caffeine: 160, size: 355 },
  { name: 'Speed Energy Fuel', category: 'Energy Drink', caffeine: 186, size: 473 },
  { name: 'Spider Energy Drink', category: 'Energy Drink', caffeine: 240, size: 473 },
  { name: 'Spike Energy Double Shot', category: 'Energy Drink', caffeine: 350, size: 126 },
  { name: 'Spike Hardcore Energy', category: 'Energy Drink', caffeine: 350, size: 473 },
  { name: 'Spike Shooter', category: 'Energy Drink', caffeine: 300, size: 355 },
  { name: 'Sprecher Cherry Cola', category: 'Soda', caffeine: 0, size: 473 },
  { name: 'Squirt Soda', category: 'Soda', caffeine: 0, size: 355 },
  { name: 'Stacker Extreme Energy Shot', category: 'Energy Drink', caffeine: 205, size: 59 },
  { name: 'Starbucks 2X Coffee Pods', category: 'Coffee', caffeine: 260, size: 237 },
  { name: 'Starbucks Bottled Iced Coffee', category: 'Coffee', caffeine: 640, size: 1420 },
  { name: 'Starbucks Canned Nitro Cold Brew', category: 'Coffee', caffeine: 235, size: 325 },
  { name: 'Starbucks Caramel Macchiato', category: 'Coffee', caffeine: 150, size: 473 },
  { name: 'Starbucks Cold & Crafted', category: 'Coffee', caffeine: 135, size: 325 },
  { name: 'Starbucks Cold Brew Bottled', category: 'Coffee', caffeine: 180, size: 325 },
  { name: 'Starbucks Cold Brew Canned', category: 'Coffee', caffeine: 165, size: 325 },
  { name: 'Starbucks Cordusio Mocha', category: 'Coffee', caffeine: 155, size: 237 },
  { name: 'Starbucks Doubleshot Energy', category: 'Energy Drink', caffeine: 135, size: 444 },
  { name: 'Starbucks Doubleshot Espresso', category: 'Coffee', caffeine: 120, size: 192 },
  { name: 'Starbucks Frappuccino (Bottled)', category: 'Coffee', caffeine: 110, size: 405 },
  { name: 'Starbucks Iced Espresso Classics', category: 'Coffee', caffeine: 125, size: 355 },
  { name: 'Starbucks Pink Drink', category: 'Other', caffeine: 45, size: 473 },
  { name: 'Starbucks Pumpkin Cream Cold Brew', category: 'Coffee', caffeine: 185, size: 473 },
  { name: 'Starbucks Refreshers Canned', category: 'Energy Drink', caffeine: 50, size: 355 },
  { name: 'Starbucks Triple Shot Energy', category: 'Coffee', caffeine: 225, size: 444 },
  { name: 'Starbucks Verismo Coffee Pods', category: 'Coffee', caffeine: 60, size: 237 },
  { name: 'Starbucks Via Ready Brew', category: 'Coffee', caffeine: 135, size: 237 },
  { name: 'Steaz Energy', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Steep 18 Cold Brew', category: 'Coffee', caffeine: 90, size: 237 },
  { name: 'Sting Energy Drink', category: 'Energy Drink', caffeine: 72, size: 250 },
  { name: 'Stipe Miocic Extra Strength Coffee', category: 'Coffee', caffeine: 500, size: 355 },
  { name: 'Stok Coffee Shots', category: 'Coffee', caffeine: 40, size: 13 },
  { name: 'Stok Cold Brew', category: 'Coffee', caffeine: 145, size: 405 },
  { name: 'Strike Force Energy Drink Mix', category: 'Energy Drink', caffeine: 160, size: 500 },
  { name: 'Stumptown Cold Brew Coffee', category: 'Coffee', caffeine: 279, size: 311 },
  { name: 'Stumptown Nitro Cold Brew', category: 'Coffee', caffeine: 330, size: 325 },
  { name: 'Sudden Instant Coffee', category: 'Coffee', caffeine: 95, size: 355 },
  { name: 'Sun Drop Soda', category: 'Soda', caffeine: 64, size: 355 },
  { name: 'Sunkist Orange Soda', category: 'Soda', caffeine: 19, size: 355 },
  { name: 'Sunup Pure Green Coffee', category: 'Coffee', caffeine: 200, size: 325 },
  { name: 'T-Virus Antidote', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'Taft Coffee (EU)', category: 'Coffee', caffeine: 1182, size: 355 },
  { name: 'Taiwanese Milk Tea', category: 'Tea', caffeine: 151, size: 473 },
  { name: 'Taster\'s Choice Instant Coffee', category: 'Coffee', caffeine: 49, size: 237 },
  { name: 'Taurus Energy Drink', category: 'Energy Drink', caffeine: 50, size: 250 },
  { name: 'Tazo Chai', category: 'Tea', caffeine: 47, size: 237 },
  { name: 'Tea (Black)', category: 'Tea', caffeine: 42, size: 237 },
  { name: 'Tea (Decaf)', category: 'Tea', caffeine: 4, size: 237 },
  { name: 'Tea (Green)', category: 'Tea', caffeine: 18, size: 237 },
  { name: 'Tea (Iced)', category: 'Tea', caffeine: 47, size: 237 },
  { name: 'Tea (Instant)', category: 'Tea', caffeine: 40, size: 237 },
  { name: 'Tea (Jasmine)', category: 'Tea', caffeine: 25, size: 237 },
  { name: 'Tea (Oolong)', category: 'Tea', caffeine: 37, size: 237 },
  { name: 'Tea (White)', category: 'Tea', caffeine: 28, size: 237 },
  { name: 'Teas\' Tea Oolong', category: 'Tea', caffeine: 70, size: 500 },
  { name: 'Teavana Tea', category: 'Tea', caffeine: 41, size: 237 },
  { name: 'Tejava Iced Tea', category: 'Tea', caffeine: 50, size: 355 },
  { name: 'TENZING Natural Energy', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Tiger Energy Drink', category: 'Energy Drink', caffeine: 75, size: 247 },
  { name: 'Tim Hortons Large Brewed Coffee', category: 'Coffee', caffeine: 270, size: 591 },
  { name: 'Tim Hortons Small French Vanilla Coffee', category: 'Coffee', caffeine: 60, size: 296 },
  { name: 'Tonic Water', category: 'Soda', caffeine: 0, size: 296 },
  { name: 'Triton Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473 },
  { name: 'Tropicana Twister Soda', category: 'Soda', caffeine: 0, size: 591 },
  { name: 'Tru Energy Wakeup', category: 'Energy Drink', caffeine: 100, size: 355 },
  { name: 'TruBrain Extra', category: 'Energy Drink', caffeine: 100, size: 30 },
  { name: 'True Lemon Energy Mix', category: 'Energy Drink', caffeine: 120, size: 473 },
  { name: 'TrueStart Performance Coffee', category: 'Coffee', caffeine: 95, size: 151 },
  { name: 'Turkey Hill Iced Tea', category: 'Tea', caffeine: 64, size: 355 },
  { name: 'Turkish Coffee', category: 'Coffee', caffeine: 50, size: 59 },
  { name: 'Tweaker Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Tweaker Shot', category: 'Energy Drink', caffeine: 275, size: 59 },
  { name: 'Twig Tea (Kukicha)', category: 'Tea', caffeine: 25, size: 237 },
  { name: 'Ugly Energy Water', category: 'Other', caffeine: 160, size: 473 },
  { name: 'UPTIME Energy Drink', category: 'Energy Drink', caffeine: 142, size: 355 },
  { name: 'USANA Rev3 Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'V Iced Coffee', category: 'Coffee', caffeine: 155, size: 500 },
  { name: 'V Energy Drink', category: 'Energy Drink', caffeine: 78, size: 250 },
  { name: 'V8 +Energy Drink', category: 'Energy Drink', caffeine: 80, size: 237 },
  { name: 'Venom Death Adder', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Vernors Ginger Ale', category: 'Soda', caffeine: 0, size: 355 },
  { name: 'Very Strong Coffee', category: 'Coffee', caffeine: 1350, size: 355 },
  { name: 'Virtue Clean Energy Beverage', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Viso Energy Drink', category: 'Energy Drink', caffeine: 300, size: 503 },
  { name: 'Vital 4U Liquid Energy', category: 'Other', caffeine: 155, size: 15 },
  { name: 'VitaminWater Energy', category: 'Energy Drink', caffeine: 50, size: 591 },
  { name: 'VitaRain Zero Enhanced Water', category: 'Other', caffeine: 42, size: 591 },
  { name: 'Voila Instant Coffee', category: 'Coffee', caffeine: 100, size: 237 },
  { name: 'Vuum', category: 'Energy Drink', caffeine: 135, size: 355 },
  { name: 'Waka Decaf Instant Coffee', category: 'Coffee', caffeine: 4, size: 237 },
  { name: 'Waka Indian Instant Coffee', category: 'Coffee', caffeine: 70, size: 237 },
  { name: 'Waka Instant Coffee', category: 'Coffee', caffeine: 70, size: 237 },
  { name: 'Waka Instant Tea', category: 'Tea', caffeine: 30, size: 237 },
  { name: 'Water Joe', category: 'Other', caffeine: 70, size: 591 },
  { name: 'Wave Soda', category: 'Soda', caffeine: 42, size: 355 },
  { name: 'Wawa Coffee', category: 'Coffee', caffeine: 290, size: 473 },
  { name: 'Wendy\'s Iced Tea', category: 'Tea', caffeine: 32, size: 473 },
  { name: 'Whipped (Dalgona) Coffee', category: 'Coffee', caffeine: 105, size: 237 },
  { name: 'Wide Awake Coffee Cold Brew', category: 'Coffee', caffeine: 120, size: 325 },
  { name: 'Wide Awake Energy Coffee', category: 'Coffee', caffeine: 180, size: 444 },
  { name: 'Wide Awake Iced Coffee Drinks', category: 'Coffee', caffeine: 30, size: 405 },
  { name: 'Wild Cherry Pepsi', category: 'Soda', caffeine: 38, size: 355 },
  { name: 'Wild Tiger Energy Drink', category: 'Energy Drink', caffeine: 75, size: 247 },
  { name: 'Wildcat Energy Drink (UK)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'Wired X 3000 Energy Drink', category: 'Energy Drink', caffeine: 185, size: 473 },
  { name: 'Wired X Berry Rush', category: 'Energy Drink', caffeine: 95, size: 473 },
  { name: 'Wired X344 Energy Drink', category: 'Energy Drink', caffeine: 344, size: 473 },
  { name: 'Woke Up Energy Shot', category: 'Energy Drink', caffeine: 225, size: 57 },
  { name: 'X Ray Energy Drink', category: 'Energy Drink', caffeine: 79, size: 250 },
  { name: 'X-Mode Energy Shot', category: 'Energy Drink', caffeine: 150, size: 30 },
  { name: 'Xing Craft Brew', category: 'Other', caffeine: 120, size: 473 },
  { name: 'Xingtea Iced Green Tea', category: 'Tea', caffeine: 110, size: 695 },
  { name: 'XL Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250 },
  { name: 'XS Energy Drink', category: 'Energy Drink', caffeine: 80, size: 248 },
  { name: 'Xyience Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Yellow Tea', category: 'Tea', caffeine: 63, size: 237 },
  { name: 'Yerba Mate Tea', category: 'Tea', caffeine: 40, size: 237 },
  { name: 'Yerbae Sparkling Water', category: 'Other', caffeine: 100, size: 355 },
  { name: 'YMateina Yerba Mate', category: 'Tea', caffeine: 80, size: 237 },
  { name: 'Zest Highly Caffeinated Tea', category: 'Tea', caffeine: 150, size: 237 },
  { name: 'Zest Sparkling Tea', category: 'Tea', caffeine: 135, size: 355 },
  { name: 'Zevia Cola', category: 'Soda', caffeine: 45, size: 355 },
  { name: 'Zevia Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355 },
  { name: 'ZipFizz Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 473 },
  { name: 'Zoa Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473 },
  { name: 'Zola Coconut Water Espresso', category: 'Coffee', caffeine: 125, size: 518 },
  { name: 'Zombie Blood Energy Potion', category: 'Energy Drink', caffeine: 80, size: 101 },