
import type { Drink } from './types';
import { Coffee, CupSoda, Leaf, Zap, Pill, Beaker } from 'lucide-react';

export const drinks: Drink[] = [
  // Coffee (Generic)
  { id: 'd1', name: 'Brewed Coffee', category: 'Coffee', caffeine: 95, size: 240, icon: Coffee },
  { id: 'd2', name: 'Espresso', category: 'Coffee', caffeine: 64, size: 30, icon: Coffee },
  { id: 'd3', name: 'Latte / Cappuccino', category: 'Coffee', caffeine: 64, size: 240, icon: Coffee },
  { id: 'd9', name: 'Decaf Coffee', category: 'Coffee', caffeine: 7, size: 240, icon: Coffee },
  { id: 'd10', name: 'Cold Brew', category: 'Coffee', caffeine: 200, size: 355, icon: Coffee },
  { id: 'd11', name: 'Instant Coffee', category: 'Coffee', caffeine: 62, size: 240, icon: Coffee },
  { id: 'd12', name: 'Iced Coffee', category: 'Coffee', caffeine: 165, size: 355, icon: Coffee },
  { id: 'd13', name: 'Americano', category: 'Coffee', caffeine: 154, size: 355, icon: Coffee },
  { id: 'd14', name: 'Mocha', category: 'Coffee', caffeine: 80, size: 355, icon: Coffee },
  { id: 'd15', name: 'Macchiato', category: 'Coffee', caffeine: 64, size: 60, icon: Coffee },
  { id: 'd16', name: 'Flat White', category: 'Coffee', caffeine: 130, size: 180, icon: Coffee },
  { id: 'd17', name: 'Nitro Cold Brew', category: 'Coffee', caffeine: 280, size: 355, icon: Coffee },

  // Tea
  { id: 'd4', name: 'Black Tea', category: 'Tea', caffeine: 47, size: 240, icon: Leaf },
  { id: 'd5', name: 'Green Tea', category: 'Tea', caffeine: 28, size: 240, icon: Leaf },
  { id: 'd18', name: 'White Tea', category: 'Tea', caffeine: 15, size: 240, icon: Leaf },
  { id: 'd19', name: 'Oolong Tea', category: 'Tea', caffeine: 37, size: 240, icon: Leaf },
  { id: 'd20', name: 'Matcha Tea', category: 'Tea', caffeine: 70, size: 240, icon: Leaf },
  { id: 'd21', name: 'Iced Tea (Black)', category: 'Tea', caffeine: 25, size: 355, icon: Leaf },
  { id: 'd22', name: 'Chai Tea Latte', category: 'Tea', caffeine: 95, size: 355, icon: Leaf },
  { id: 'd23', name: 'Herbal Tea', category: 'Tea', caffeine: 0, size: 240, icon: Leaf },

  // Soda
  { id: 'd6', name: 'Cola (Generic)', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd24', name: 'Coca-Cola Classic', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd25', name: 'Diet Coke', category: 'Soda', caffeine: 46, size: 355, icon: CupSoda },
  { id: 'd26', name: 'Coke Zero', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd27', name: 'Pepsi', category: 'Soda', caffeine: 38, size: 355, icon: CupSoda },
  { id: 'd28', name: 'Diet Pepsi', category: 'Soda', caffeine: 36, size: 355, icon: CupSoda },
  { id: 'd29', name: 'Dr Pepper', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd30', name: 'Diet Dr Pepper', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd31', name: 'Mountain Dew', category: 'Soda', caffeine: 54, size: 355, icon: CupSoda },
  { id: 'd32', name: 'Diet Mountain Dew', category: 'Soda', caffeine: 54, size: 355, icon: CupSoda },
  { id: 'd33', name: 'Sprite', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'd34', name: '7 Up', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'd35', name: 'Sunkist Orange', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd36', name: 'A&W Cream Soda', category: 'Soda', caffeine: 29, size: 355, icon: CupSoda },
  { id: 'd37', name: 'Barq\'s Root Beer', category: 'Soda', caffeine: 22, size: 355, icon: CupSoda },

  // Energy Drinks
  { id: 'd7', name: 'Energy Drink (Generic)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd8', name: 'Energy Shot (Generic)', category: 'Energy Drink', caffeine: 200, size: 60, icon: Zap },
  { id: 'd38', name: 'Red Bull (250ml)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd39', name: 'Red Bull (355ml)', category: 'Energy Drink', caffeine: 114, size: 355, icon: Zap },
  { id: 'd40', name: 'Red Bull Sugarfree (250ml)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd41', name: 'Monster Energy (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd42', name: 'Monster Lo-Carb (473ml)', category: 'Energy Drink', caffeine: 140, size: 473, icon: Zap },
  { id: 'd43', name: 'Monster Zero Ultra (473ml)', category: 'Energy Drink', caffeine: 140, size: 473, icon: Zap },
  { id: 'd44', name: 'Rockstar (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd45', name: 'Rockstar Sugar Free (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd46', name: 'Bang Energy (473ml)', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'd47', name: '5-Hour Energy', category: 'Energy Drink', caffeine: 200, size: 57, icon: Zap },
  { id: 'd48', name: '5-Hour Energy Extra Strength', category: 'Energy Drink', caffeine: 230, size: 57, icon: Zap },
  { id: 'd49', name: 'Celsius (355ml)', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'd50', name: 'Reign Total Body Fuel (473ml)', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'd51', name: 'VPX Bang', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'monster-1', name: 'Caffe Monster Energy Coffee', category: 'Coffee', caffeine: 175, size: 405, icon: Coffee },
  { id: 'monster-2', name: 'Monster Cuba Lima', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'monster-3', name: 'Monster DUB', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'monster-4', name: 'Monster Export (UK)', category: 'Energy Drink', caffeine: 76, size: 250, icon: Zap },
  { id: 'monster-5', name: 'Monster Hammer X-presso', category: 'Coffee', caffeine: 221, size: 200, icon: Coffee },
  { id: 'monster-6', name: 'Monster Heavy Metal', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'monster-7', name: 'Monster Hitman Sniper', category: 'Energy Drink', caffeine: 240, size: 89, icon: Zap },
  { id: 'monster-8', name: 'Monster Khaos', category: 'Energy Drink', caffeine: 154, size: 473, icon: Zap },
  { id: 'monster-9', name: 'Monster M3 Energy Drink', category: 'Energy Drink', caffeine: 160, size: 148, icon: Zap },
  { id: 'monster-10', name: 'Monster Maxx', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'monster-11', name: 'Monster Mixxd Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'monster-12', name: 'Monster Mutant Super Soda', category: 'Soda', caffeine: 115, size: 591, icon: CupSoda },
  { id: 'monster-13', name: 'Monster Rehab Green Tea', category: 'Tea', caffeine: 155, size: 458, icon: Leaf },
  { id: 'monster-14', name: 'Monster Ultra Pink', category: 'Energy Drink', caffeine: 140, size: 473, icon: Zap },
  { id: 'monster-15', name: 'Monster Unleaded', category: 'Energy Drink', caffeine: 0, size: 473, icon: Zap },
  { id: 'monster-16', name: 'Monster X-presso Hammer (NZ/AUS)', category: 'Coffee', caffeine: 90, size: 284, icon: Coffee },
  { id: 'monster-17', name: 'Ubermonster Energy Brew', category: 'Energy Drink', caffeine: 187, size: 550, icon: Zap },

  // Starbucks (Popular Sizes: Short 236ml, Tall 355ml, Grande 473ml, Venti 591ml)
  { id: 's1', name: 'Starbucks Brewed Coffee (Grande)', category: 'Coffee', caffeine: 310, size: 473, icon: Coffee },
  { id: 's2', name: 'Starbucks Blonde Roast (Grande)', category: 'Coffee', caffeine: 360, size: 473, icon: Coffee },
  { id: 's3', name: 'Starbucks Pike Place (Grande)', category: 'Coffee', caffeine: 310, size: 473, icon: Coffee },
  { id: 's4', name: 'Starbucks Decaf Pike Place (Grande)', category: 'Coffee', caffeine: 25, size: 473, icon: Coffee },
  { id: 's5', name: 'Starbucks Espresso Shot', category: 'Coffee', caffeine: 75, size: 22, icon: Coffee },
  { id: 's6', name: 'Starbucks Caffe Latte (Grande)', category: 'Coffee', caffeine: 150, size: 473, icon: Coffee },
  { id: 's7', name: 'Starbucks Cappuccino (Grande)', category: 'Coffee', caffeine: 150, size: 473, icon: Coffee },
  { id: 's8', name: 'Starbucks Caffe Americano (Grande)', category: 'Coffee', caffeine: 225, size: 473, icon: Coffee },
  { id: 's9', name: 'Starbucks Flat White (Grande)', category: 'Coffee', caffeine: 195, size: 473, icon: Coffee },
  { id: 's10', name: 'Starbucks Caffe Mocha (Grande)', category: 'Coffee', caffeine: 175, size: 473, icon: Coffee },
  { id: 's11', name: 'Starbucks Iced Coffee (Grande)', category: 'Coffee', caffeine: 165, size: 473, icon: Coffee },
  { id: 's12', name: 'Starbucks Cold Brew (Grande)', category: 'Coffee', caffeine: 205, size: 473, icon: Coffee },
  { id: 's13', name: 'Starbucks Nitro Cold Brew (Grande)', category: 'Coffee', caffeine: 280, size: 473, icon: Coffee },
  { id: 's14', name: 'Starbucks Doubleshot on Ice', category: 'Coffee', caffeine: 150, size: 236, icon: Coffee },
  { id: 's15', name: 'Starbucks Frappuccino Coffee (Grande)', category: 'Coffee', caffeine: 95, size: 473, icon: Coffee },
  { id: 's16', name: 'Starbucks Iced Shaken Espresso (Grande)', category: 'Coffee', caffeine: 225, size: 473, icon: Coffee },
  { id: 's17', name: 'Starbucks Chai Tea Latte (Grande)', category: 'Tea', caffeine: 95, size: 473, icon: Leaf },
  { id: 's18', name: 'Starbucks Matcha Tea Latte (Grande)', category: 'Tea', caffeine: 80, size: 473, icon: Leaf },
  { id: 's19', name: 'Starbucks Black Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473, icon: Leaf },
  { id: 's20', name: 'Starbucks Green Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473, icon: Leaf },
  { id: 's21', name: 'Starbucks Refresher (Grande)', category: 'Energy Drink', caffeine: 45, size: 473, icon: Zap },

  // Dunkin' (Popular Sizes: Small 296ml, Medium 414ml, Large 591ml)
  { id: 'dunk1', name: 'Dunkin\' Brewed Coffee (Medium)', category: 'Coffee', caffeine: 210, size: 414, icon: Coffee },
  { id: 'dunk2', name: 'Dunkin\' Decaf Coffee (Medium)', category: 'Coffee', caffeine: 10, size: 414, icon: Coffee },
  { id: 'dunk3', name: 'Dunkin\' Americano (Medium)', category: 'Coffee', caffeine: 284, size: 414, icon: Coffee },
  { id: 'dunk4', name: 'Dunkin\' Latte (Medium)', category: 'Coffee', caffeine: 166, size: 414, icon: Coffee },
  { id: 'dunk5', name: 'Dunkin\' Cappuccino (Medium)', category: 'Coffee', caffeine: 166, size: 414, icon: Coffee },
  { id: 'dunk6', name: 'Dunkin\' Espresso Shot', category: 'Coffee', caffeine: 98, size: 30, icon: Coffee },
  { id: 'dunk7', name: 'Dunkin\' Iced Coffee (Medium)', category: 'Coffee', caffeine: 297, size: 710, icon: Coffee },
  { id: 'dunk8', name: 'Dunkin\' Cold Brew (Medium)', category: 'Coffee', caffeine: 260, size: 710, icon: Coffee },
  { id: 'dunk9', name: 'Dunkin\' Frozen Coffee (Medium)', category: 'Coffee', caffeine: 295, size: 710, icon: Coffee },
  { id: 'dunk10', name: 'Dunkin\' Macchiato (Medium)', category: 'Coffee', caffeine: 284, size: 414, icon: Coffee },
  { id: 'dunk11', name: 'Dunkin\' Chai Latte (Medium)', category: 'Tea', caffeine: 108, size: 414, icon: Leaf },

  // McDonald's (Popular Sizes: Small 355ml, Medium 473ml, Large 621ml)
  { id: 'mcd1', name: 'McDonald\'s McCafé Coffee (Medium)', category: 'Coffee', caffeine: 145, size: 473, icon: Coffee },
  { id: 'mcd2', name: 'McDonald\'s Iced Coffee (Medium)', category: 'Coffee', caffeine: 133, size: 473, icon: Coffee },
  { id: 'mcd3', name: 'McDonald\'s Latte (Medium)', category: 'Coffee', caffeine: 142, size: 473, icon: Coffee },
  { id: 'mcd4', name: 'McDonald\'s Americano (Medium)', category: 'Coffee', caffeine: 114, size: 473, icon: Coffee },
  { id: 'mcd5', name: 'McDonald\'s Espresso Shot', category: 'Coffee', caffeine: 71, size: 30, icon: Coffee },
  { id: 'mcd6', name: 'McDonald\'s Frappé (Medium)', category: 'Coffee', caffeine: 130, size: 473, icon: Coffee },
  { id: 'mcd7', name: 'McDonald\'s Sweet Tea (Medium)', category: 'Tea', caffeine: 100, size: 621, icon: Leaf },

  // Other Common Caffeinated Items
  { id: 'oth1', name: 'Dark Chocolate (1 oz / 28g)', category: 'Other', caffeine: 24, size: 28, icon: Beaker },
  { id: 'oth2', name: 'Milk Chocolate (1 oz / 28g)', category: 'Other', caffeine: 6, size: 28, icon: Beaker },
  { id: 'oth3', name: 'Hot Chocolate (240ml)', category: 'Other', caffeine: 5, size: 240, icon: Coffee },
  { id: 'oth4', name: 'Caffeine Pill', category: 'Other', caffeine: 200, size: 1, icon: Pill },
  { id: 'oth5', name: 'Pre-Workout Supplement (1 scoop)', category: 'Other', caffeine: 150, size: 10, icon: Beaker },
  { id: 'oth6', name: 'NoDoz Max Strength', category: 'Other', caffeine: 200, size: 1, icon: Pill },
  { id: 'oth7', name: 'Excedrin Migraine (2 tablets)', category: 'Other', caffeine: 130, size: 2, icon: Pill },
  { id: 'oth8', name: 'Guayaki Yerba Mate (458ml can)', category: 'Tea', caffeine: 150, size: 458, icon: Leaf },
  { id: 'oth9', name: 'Kombucha (240ml)', category: 'Tea', caffeine: 15, size: 240, icon: Leaf },
  { id: 'oth10', name: 'Caffeinated Water (e.g., Water Joe)', category: 'Other', caffeine: 70, size: 500, icon: CupSoda },
  { id: 'oth11', name: 'Clif Shot Energy Gel (with caffeine)', category: 'Other', caffeine: 50, size: 34, icon: Beaker },
  
  // New Additions
  { id: 'new-d1', name: '28 Black Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d2', name: '3 Water', category: 'Other', caffeine: 50, size: 500, icon: CupSoda },
  { id: 'new-d3', name: '3D Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473, icon: Zap },
  { id: 'new-d4', name: '4 Purpose Energy Drink', category: 'Energy Drink', caffeine: 70, size: 250, icon: Zap },
  { id: 'new-d5', name: '4C Energy Drink Mix', category: 'Energy Drink', caffeine: 170, size: 500, icon: Zap },
  { id: 'new-d6', name: '5 Hour Energy', category: 'Energy Drink', caffeine: 200, size: 57, icon: Zap },
  { id: 'new-d7', name: '5 Hour Energy Extra Strength', category: 'Energy Drink', caffeine: 230, size: 57, icon: Zap },
  { id: 'new-d8', name: '7 Eleven Brewed Coffee', category: 'Coffee', caffeine: 280, size: 473, icon: Coffee },
  { id: 'new-d9', name: '7-Eleven Energy Shot', category: 'Energy Drink', caffeine: 260, size: 59, icon: Zap },
  { id: 'new-d10', name: '7-Up', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d11', name: 'A Shoc', category: 'Energy Drink', caffeine: 250, size: 473, icon: Zap },
  { id: 'new-d12', name: 'A&W Zero Sugar Cream Soda', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d13', name: 'ABB Turbo Tea Zero', category: 'Tea', caffeine: 120, size: 532, icon: Leaf },
  { id: 'new-d14', name: 'Accelerator', category: 'Energy Drink', caffeine: 150, size: 355, icon: Zap },
  { id: 'new-d15', name: 'Advocare Slam Energy Shot', category: 'Energy Drink', caffeine: 120, size: 59, icon: Zap },
  { id: 'new-d16', name: 'Advocare Slim', category: 'Energy Drink', caffeine: 120, size: 237, icon: Zap },
  { id: 'new-d17', name: 'Afri Cola', category: 'Soda', caffeine: 83, size: 330, icon: CupSoda },
  { id: 'new-d18', name: 'AHA Sparkling Water', category: 'Other', caffeine: 30, size: 355, icon: CupSoda },
  { id: 'new-d19', name: 'Alani Nu Energy Drink', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'new-d20', name: 'Ale 8 1', category: 'Soda', caffeine: 37, size: 355, icon: CupSoda },
  { id: 'new-d21', name: 'ALL IN Energy Drink', category: 'Energy Drink', caffeine: 75, size: 355, icon: Zap },
  { id: 'new-d22', name: 'Alpine Start Instant Coffee', category: 'Coffee', caffeine: 120, size: 237, icon: Coffee },
  { id: 'new-d23', name: 'Alsa Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 473, icon: Zap },
  { id: 'new-d24', name: 'Americano Coffee', category: 'Coffee', caffeine: 154, size: 355, icon: Coffee },
  { id: 'new-d25', name: 'AMIN.O. Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355, icon: Zap },
  { id: 'new-d26', name: 'Amino Force Energy Drink', category: 'Energy Drink', caffeine: 200, size: 651, icon: Zap },
  { id: 'new-d27', name: 'Arbonne Energy Fizz Stck', category: 'Energy Drink', caffeine: 55, size: 237, icon: Zap },
  { id: 'new-d28', name: 'Arby\'s Jamocha Shake', category: 'Coffee', caffeine: 12, size: 473, icon: Coffee },
  { id: 'new-d29', name: 'Arizona Arnold Palmer Half and Half', category: 'Tea', caffeine: 15, size: 500, icon: Leaf },
  { id: 'new-d30', name: 'Arizona Energy Drink Rx', category: 'Energy Drink', caffeine: 127, size: 340, icon: Zap },
  { id: 'new-d31', name: 'Arizona Iced Tea', category: 'Tea', caffeine: 30, size: 473, icon: Leaf },
  { id: 'new-d32', name: 'Arti Sparkling Water', category: 'Other', caffeine: 120, size: 355, icon: CupSoda },
  { id: 'new-d33', name: 'AXIO Energy Drink Mix', category: 'Energy Drink', caffeine: 100, size: 355, icon: Zap },
  { id: 'new-d34', name: 'Bai Antioxidant Infusion', category: 'Other', caffeine: 55, size: 532, icon: CupSoda },
  { id: 'new-d35', name: 'Bai Boost', category: 'Energy Drink', caffeine: 110, size: 340, icon: Zap },
  { id: 'new-d36', name: 'Balance Active Shot', category: 'Energy Drink', caffeine: 100, size: 59, icon: Zap },
  { id: 'new-d37', name: 'Balance Energy Shot', category: 'Energy Drink', caffeine: 150, size: 59, icon: Zap },
  { id: 'new-d38', name: 'Bang Keto Coffee', category: 'Coffee', caffeine: 300, size: 473, icon: Coffee },
  { id: 'new-d39', name: 'Bang Natural', category: 'Energy Drink', caffeine: 250, size: 473, icon: Zap },
  { id: 'new-d40', name: 'Bang Shot', category: 'Energy Drink', caffeine: 300, size: 89, icon: Zap },
  { id: 'new-d41', name: 'Bang Sweet Tea', category: 'Tea', caffeine: 300, size: 473, icon: Leaf },
  { id: 'new-d42', name: 'Barista Bros Iced Coffee', category: 'Coffee', caffeine: 140, size: 500, icon: Coffee },
  { id: 'new-d43', name: 'Barqs Red Creme Soda', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d44', name: 'Baskin Robbins Cappuccino Blast', category: 'Coffee', caffeine: 234, size: 710, icon: Coffee },
  { id: 'new-d45', name: 'Bawls', category: 'Energy Drink', caffeine: 102, size: 473, icon: Zap },
  { id: 'new-d46', name: 'BE Beyond Energy Drink', category: 'Energy Drink', caffeine: 160, size: 355, icon: Zap },
  { id: 'new-d47', name: 'Beaver Buzz Energy Drink', category: 'Energy Drink', caffeine: 178, size: 473, icon: Zap },
  { id: 'new-d48', name: 'BEEBAD Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d49', name: 'Berocca', category: 'Other', caffeine: 90, size: 237, icon: Beaker },
  { id: 'new-d50', name: 'Berzerk Energy Drink Mix', category: 'Energy Drink', caffeine: 200, size: 473, icon: Zap },
  { id: 'new-d51', name: 'Best Choice Strawberry Energy Drink Mix', category: 'Energy Drink', caffeine: 120, size: 237, icon: Zap },
  { id: 'new-d52', name: 'Big Red Soda', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d53', name: 'Big Train Java Chip Ice Coffee', category: 'Coffee', caffeine: 49, size: 355, icon: Coffee },
  { id: 'new-d54', name: 'Big Train Spiced Chai', category: 'Tea', caffeine: 65, size: 237, icon: Leaf },
  { id: 'new-d55', name: 'Bigelow Tea', category: 'Tea', caffeine: 45, size: 237, icon: Leaf },
  { id: 'new-d56', name: 'Biggby Brewed Coffee', category: 'Coffee', caffeine: 200, size: 473, icon: Coffee },
  { id: 'new-d57', name: 'Biggby Creamy Lattes', category: 'Coffee', caffeine: 100, size: 473, icon: Coffee },
  { id: 'new-d58', name: 'Biggby Espresso', category: 'Coffee', caffeine: 100, size: 59, icon: Coffee },
  { id: 'new-d59', name: 'Biggby Iced Coffee', category: 'Coffee', caffeine: 155, size: 473, icon: Coffee },
  { id: 'new-d60', name: 'Biggby Iced Tea', category: 'Tea', caffeine: 38, size: 473, icon: Leaf },
  { id: 'new-d61', name: 'Bing Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355, icon: Zap },
  { id: 'new-d62', name: 'Bizzy Cold Brew', category: 'Coffee', caffeine: 125, size: 79, icon: Coffee },
  { id: 'new-d63', name: 'Black Bruin Energy Drink', category: 'Energy Drink', caffeine: 38, size: 250, icon: Zap },
  { id: 'new-d64', name: 'Black Ink Coffee', category: 'Coffee', caffeine: 144, size: 355, icon: Coffee },
  { id: 'new-d65', name: 'Black Insomnia Coffee', category: 'Coffee', caffeine: 1105, size: 355, icon: Coffee },
  { id: 'new-d66', name: 'Black Label Brewed Coffee', category: 'Coffee', caffeine: 1555, size: 355, icon: Coffee },
  { id: 'new-d67', name: 'Bloom Energy', category: 'Energy Drink', caffeine: 180, size: 355, icon: Zap },
  { id: 'new-d68', name: 'Blu Frog Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d69', name: 'Blue Bolt (UK)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d70', name: 'Blue Charge (UK)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d71', name: 'Blue Spark (UK)', category: 'Energy Drink', caffeine: 75, size: 250, icon: Zap },
  { id: 'new-d72', name: 'Bodyarmour Edge', category: 'Energy Drink', caffeine: 100, size: 591, icon: Zap },
  { id: 'new-d73', name: 'Bomb Energy Drink', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d74', name: 'Bomba (EU)', category: 'Energy Drink', caffeine: 80, size: 248, icon: Zap },
  { id: 'new-d75', name: 'Boost Energy (UK)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d76', name: 'Boost Nutritional Drink', category: 'Other', caffeine: 5, size: 237, icon: Beaker },
  { id: 'new-d77', name: 'Bottled Iced Coffee Dunkin Donuts', category: 'Coffee', caffeine: 197, size: 405, icon: Coffee },
  { id: 'new-d78', name: 'BPM Energy Drink', category: 'Energy Drink', caffeine: 70, size: 500, icon: Zap },
  { id: 'new-d79', name: 'BreinFuel', category: 'Energy Drink', caffeine: 360, size: 355, icon: Zap },
  { id: 'new-d80', name: 'Brew Dr Kombucha Uplift', category: 'Tea', caffeine: 130, size: 414, icon: Leaf },
  { id: 'new-d81', name: 'Brisk Iced Tea', category: 'Tea', caffeine: 11, size: 355, icon: Leaf },
  { id: 'new-d82', name: 'Brown Rice Tea', category: 'Tea', caffeine: 4, size: 237, icon: Leaf },
  { id: 'new-d83', name: 'Bubbl\'r Sparkling Water', category: 'Other', caffeine: 69, size: 355, icon: CupSoda },
  { id: 'new-d84', name: 'Bubly Bounce Sparkling Water', category: 'Other', caffeine: 35, size: 355, icon: CupSoda },
  { id: 'new-d85', name: 'Bubly Sparkling Water', category: 'Other', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d86', name: 'Bucked Up', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'new-d87', name: 'Bulletproof Coffee', category: 'Coffee', caffeine: 145, size: 237, icon: Coffee },
  { id: 'new-d88', name: 'Burn Energy Drink', category: 'Energy Drink', caffeine: 112, size: 355, icon: Zap },
  { id: 'new-d89', name: 'C4 On The Go', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'new-d90', name: 'C4 Performance Energy', category: 'Energy Drink', caffeine: 200, size: 473, icon: Zap },
  { id: 'new-d91', name: 'C4 Smart Energy Drink', category: 'Energy Drink', caffeine: 200, size: 473, icon: Zap },
  { id: 'new-d92', name: 'C4 Ultimate Energy Drink', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'new-d93', name: 'Cafe Bustelo', category: 'Coffee', caffeine: 150, size: 355, icon: Coffee },
  { id: 'new-d94', name: 'Cafe Con Leche', category: 'Coffee', caffeine: 154, size: 177, icon: Coffee },
  { id: 'new-d95', name: 'Caffe Mocha', category: 'Coffee', caffeine: 152, size: 355, icon: Coffee },
  { id: 'new-d96', name: 'Caffe Nero Coffee', category: 'Coffee', caffeine: 160, size: 355, icon: Coffee },
  { id: 'new-d97', name: 'Califia Farms Cold Brew Coffee', category: 'Coffee', caffeine: 180, size: 237, icon: Coffee },
  { id: 'new-d98', name: 'Canada Dry Green Tea Ginger Ale', category: 'Soda', caffeine: 9, size: 355, icon: CupSoda },
  { id: 'new-d99', name: 'Cannonball Coffee Maximum Charge (UK)', category: 'Coffee', caffeine: 1101, size: 355, icon: Coffee },
  { id: 'new-d100', name: 'Cappuccino', category: 'Coffee', caffeine: 154, size: 355, icon: Coffee },
  { id: 'new-d101', name: 'Carabao Energy Drink (UK)', category: 'Energy Drink', caffeine: 106, size: 330, icon: Zap },
  { id: 'new-d102', name: 'Caribou BOUsted Sparkling Water', category: 'Other', caffeine: 75, size: 340, icon: CupSoda },
  { id: 'new-d103', name: 'Caribou Brewed Coffee', category: 'Coffee', caffeine: 305, size: 473, icon: Coffee },
  { id: 'new-d104', name: 'Caribou Canned Cold Brew', category: 'Coffee', caffeine: 177, size: 340, icon: Coffee },
  { id: 'new-d105', name: 'Cascara', category: 'Tea', caffeine: 36, size: 237, icon: Leaf },
  { id: 'new-d106', name: 'CBD Coffee', category: 'Coffee', caffeine: 100, size: 237, icon: Coffee },
  { id: 'new-d107', name: 'Celsius Energy Drink', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'new-d108', name: 'Celsius Stevia', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'new-d109', name: 'Chai Tea', category: 'Tea', caffeine: 50, size: 237, icon: Leaf },
  { id: 'new-d110', name: 'Chameleon Cold Brew Coffee', category: 'Coffee', caffeine: 210, size: 237, icon: Coffee },
  { id: 'new-d111', name: 'Chameleon Cold Brew RTD', category: 'Coffee', caffeine: 230, size: 296, icon: Coffee },
  { id: 'new-d112', name: 'Chameleon Cold Brew With Milk', category: 'Coffee', caffeine: 100, size: 325, icon: Coffee },
  { id: 'new-d113', name: 'Cheerwine', category: 'Soda', caffeine: 47, size: 355, icon: CupSoda },
  { id: 'new-d114', name: 'Chick-fil-A Brewed Coffee', category: 'Coffee', caffeine: 136, size: 296, icon: Coffee },
  { id: 'new-d115', name: 'Chick-fil-A Frosted Coffee', category: 'Coffee', caffeine: 130, size: 414, icon: Coffee },
  { id: 'new-d116', name: 'Chick-fil-A Iced Coffee', category: 'Coffee', caffeine: 80, size: 414, icon: Coffee },
  { id: 'new-d117', name: 'Chick-fil-A Iced Tea', category: 'Tea', caffeine: 62, size: 473, icon: Leaf },
  { id: 'new-d118', name: 'Choffy (roasted cacao)', category: 'Other', caffeine: 23, size: 177, icon: Beaker },
  { id: 'new-d119', name: 'Cintron Energy Drink', category: 'Energy Drink', caffeine: 85, size: 248, icon: Zap },
  { id: 'new-d120', name: 'Clif Shot Energy Gel', category: 'Energy Drink', caffeine: 100, size: 35, icon: Zap },
  { id: 'new-d121', name: 'Club Mate (EU)', category: 'Energy Drink', caffeine: 100, size: 500, icon: Zap },
  { id: 'new-d122', name: 'Coca Cola Plus', category: 'Soda', caffeine: 45, size: 470, icon: CupSoda },
  { id: 'new-d123', name: 'Coca-Cola Caffeine Free', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d124', name: 'Coca-Cola Cherry', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d125', name: 'Coca-Cola Cherry Vanilla', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d126', name: 'Coca-Cola Cherry Zero Sugar', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d127', name: 'Coca-Cola Energy', category: 'Energy Drink', caffeine: 114, size: 355, icon: Zap },
  { id: 'new-d128', name: 'Coca-Cola Orange Vanilla', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d129', name: 'Coca-Cola Vanilla', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d130', name: 'Coca-Cola Vanilla Zero Sugar', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d131', name: 'Coca-Cola With Coffee', category: 'Coffee', caffeine: 69, size: 355, icon: Coffee },
  { id: 'new-d132', name: 'Coca-Cola Zero Sugar', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'new-d133', name: 'Cocaine Energy Drink', category: 'Energy Drink', caffeine: 280, size: 355, icon: Zap },
  { id: 'new-d134', name: 'Coffee (Generic)', category: 'Coffee', caffeine: 163, size: 237, icon: Coffee },
  { id: 'new-d135', name: 'Coffee (Decaf, Instant)', category: 'Coffee', caffeine: 2, size: 237, icon: Coffee },
  { id: 'new-d136', name: 'Coffee (Instant)', category: 'Coffee', caffeine: 57, size: 237, icon: Coffee },
  { id: 'new-d137', name: 'Coffee (Moka Pot)', category: 'Coffee', caffeine: 93, size: 59, icon: Coffee },
  { id: 'new-d138', name: 'Coffee Bean & Tea leaf Coffee', category: 'Coffee', caffeine: 333, size: 473, icon: Coffee },
  { id: 'new-d139', name: 'Coffee Friend Brewed Coffee', category: 'Coffee', caffeine: 145, size: 250, icon: Coffee },
  { id: 'new-d140', name: 'Coffee Leaf Tea', category: 'Tea', caffeine: 20, size: 237, icon: Leaf },
  { id: 'new-d141', name: 'COGO Caffeinated Hot Chocolate', category: 'Other', caffeine: 98, size: 177, icon: Coffee },
  { id: 'new-d142', name: 'Cold Brew Tea', category: 'Tea', caffeine: 70, size: 237, icon: Leaf },
  { id: 'new-d143', name: 'CoolBrew Coffee', category: 'Coffee', caffeine: 60, size: 296, icon: Coffee },
  { id: 'new-d144', name: 'Costa Coffee', category: 'Coffee', caffeine: 241, size: 300, icon: Coffee },
  { id: 'new-d145', name: 'Cran Energy Juice', category: 'Energy Drink', caffeine: 70, size: 296, icon: Zap },
  { id: 'new-d146', name: 'Crave Energy Drink (UK)', category: 'Energy Drink', caffeine: 80, size: 249, icon: Zap },
  { id: 'new-d147', name: 'Crio Bru Brewed Cacao', category: 'Other', caffeine: 10, size: 237, icon: Beaker },
  { id: 'new-d148', name: 'Crunk Energy Drink', category: 'Energy Drink', caffeine: 192, size: 473, icon: Zap },
  { id: 'new-d149', name: 'Crystal Light Energy Mix', category: 'Energy Drink', caffeine: 60, size: 473, icon: Zap },
  { id: 'new-d150', name: 'Crystal Light Iced Tea', category: 'Tea', caffeine: 10, size: 237, icon: Leaf },
  { id: 'new-d151', name: 'Dare Iced Coffee', category: 'Coffee', caffeine: 160, size: 500, icon: Coffee },
  { id: 'new-d152', name: 'Dark Dog Organic Energy', category: 'Energy Drink', caffeine: 114, size: 355, icon: Zap },
  { id: 'new-d153', name: 'Death Wish Canned Cold Brew', category: 'Coffee', caffeine: 300, size: 237, icon: Coffee },
  { id: 'new-d154', name: 'Death Wish Coffee', category: 'Coffee', caffeine: 728, size: 355, icon: Coffee },
  { id: 'new-d155', name: 'Death Wish Latte', category: 'Coffee', caffeine: 300, size: 237, icon: Coffee },
  { id: 'new-d156', name: 'Decaf Coffee', category: 'Coffee', caffeine: 6, size: 237, icon: Coffee },
  { id: 'new-d157', name: 'Demon Energy Drink', category: 'Energy Drink', caffeine: 160, size: 500, icon: Zap },
  { id: 'new-d158', name: 'Diet Barqs Root Beer', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'new-d159', name: 'Diet Cheerwine', category: 'Soda', caffeine: 47, size: 355, icon: CupSoda },
  { id: 'new-d160', name: 'Diet Coke with Splenda', category: 'Soda', caffeine: 46, size: 355, icon: CupSoda },
  { id: 'new-d161', name: 'Diet Pepsi', category: 'Soda', caffeine: 35, size: 355, icon: CupSoda },
  { id: 'new-d162', name: 'Diet RC Cola', category: 'Soda', caffeine: 48, size: 355, icon: CupSoda },
  { id: 'new-d163', name: 'Diet Wild Cherry Pepsi', category: 'Soda', caffeine: 38, size: 355, icon: CupSoda },
  { id: 'new-d164', name: 'doc Soda', category: 'Soda', caffeine: 60, size: 355, icon: CupSoda },
  { id: 'new-d165', name: 'Double Cola', category: 'Soda', caffeine: 36, size: 355, icon: CupSoda },
  { id: 'new-d166', name: 'Dr Pepper 10', category: 'Soda', caffeine: 51, size: 355, icon: CupSoda },
  { id: 'new-d167', name: 'Dr Pepper Zero Sugar', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'new-d168', name: 'Dr Shasta Soda', category: 'Soda', caffeine: 29, size: 355, icon: CupSoda },
  { id: 'new-d169', name: 'Driftaway Coffee', category: 'Coffee', caffeine: 160, size: 237, icon: Coffee },
  { id: 'new-d170', name: 'Dripdash Kyoto Coffee', category: 'Coffee', caffeine: 225, size: 177, icon: Coffee },
  { id: 'new-d171', name: 'Duff Energy Drink', category: 'Energy Drink', caffeine: 120, size: 355, icon: Zap },
  { id: 'new-d172', name: 'Dunkin Donuts Shot In The Dark', category: 'Coffee', caffeine: 134, size: 240, icon: Coffee },
  { id: 'new-d173', name: 'Dunkin Sparkd Energy', category: 'Energy Drink', caffeine: 192, size: 946, icon: Zap },
  { id: 'new-d174', name: 'Dunkin\' Cold Brew', category: 'Coffee', caffeine: 260, size: 710, icon: Coffee },
  { id: 'new-d175', name: 'Dunkin\' Donuts Brewed Coffee', category: 'Coffee', caffeine: 210, size: 414, icon: Coffee },
  { id: 'new-d176', name: 'Dunkin\' Donuts Dunkaccino', category: 'Coffee', caffeine: 83, size: 414, icon: Coffee },
  { id: 'new-d177', name: 'Dunkin\' Donuts Extra Charged Coffee', category: 'Coffee', caffeine: 252, size: 414, icon: Coffee },
  { id: 'new-d178', name: 'Dunkin\' Donuts Iced Coffee', category: 'Coffee', caffeine: 294, size: 710, icon: Coffee },
  { id: 'new-d179', name: 'Dunkin\' Donuts Iced Latte', category: 'Coffee', caffeine: 166, size: 710, icon: Coffee },
  { id: 'new-d180', name: 'Dunkin\' Donuts Iced Tea', category: 'Tea', caffeine: 63, size: 710, icon: Leaf },
  { id: 'new-d181', name: 'Dunkin\' Donuts Latte', category: 'Coffee', caffeine: 166, size: 414, icon: Coffee },
  { id: 'new-d182', name: 'Dutch Bros Blue Rebel Energy Drink', category: 'Energy Drink', caffeine: 80, size: 248, icon: Zap },
  { id: 'new-d183', name: 'Dutch Bros Coffee (Classic)', category: 'Coffee', caffeine: 187, size: 591, icon: Coffee },
  { id: 'new-d184', name: 'DynaPep', category: 'Energy Drink', caffeine: 100, size: 4, icon: Zap },
  { id: 'new-d185', name: 'E6 Energy Shot', category: 'Energy Drink', caffeine: 235, size: 57, icon: Zap },
  { id: 'new-d186', name: 'EBOOST Energy Drink Mix', category: 'Energy Drink', caffeine: 110, size: 237, icon: Zap },
  { id: 'new-d187', name: 'EBOOST Super Fuel', category: 'Energy Drink', caffeine: 110, size: 355, icon: Zap },
  { id: 'new-d188', name: 'EBOOST Workout Crusher Mix', category: 'Energy Drink', caffeine: 175, size: 237, icon: Zap },
  { id: 'new-d189', name: 'Eight O\'Clock Coffee', category: 'Coffee', caffeine: 112, size: 237, icon: Coffee },
  { id: 'new-d190', name: 'Einstein Bros Coffee', category: 'Coffee', caffeine: 206, size: 473, icon: Coffee },
  { id: 'new-d191', name: 'Electric Monkey Wild Energy Drink', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'new-d192', name: 'EnerBee Energy Drink', category: 'Energy Drink', caffeine: 100, size: 355, icon: Zap },
  { id: 'new-d193', name: 'Equip Pure Energy Shot', category: 'Energy Drink', caffeine: 100, size: 53, icon: Zap },
  { id: 'new-d194', name: 'Espresso Monster', category: 'Coffee', caffeine: 160, size: 248, icon: Coffee },
  { id: 'new-d195', name: 'Eternal Energy Extra Strength', category: 'Energy Drink', caffeine: 280, size: 57, icon: Zap },
  { id: 'new-d196', name: 'Eternal Energy Shot', category: 'Energy Drink', caffeine: 230, size: 57, icon: Zap },
  { id: 'new-d197', name: 'Euro Shopper Energy Drink (EU)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'new-d198', name: 'F3 Energy', category: 'Energy Drink', caffeine: 120, size: 355, icon: Zap },
  { id: 'new-d199', name: 'Fakeer Energy Drink (EU)', category: 'Energy Drink', caffeine: 118, size: 370, icon: Zap },
  { id: 'new-d200', name: 'Fanta', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda }
];
