import type { Drink } from './types';
import { Coffee, CupSoda, Leaf, Zap, Pill, Beaker } from 'lucide-react';

export const drinks: Drink[] = [
  // Coffee (Generic)
  { id: 'd1', name: 'Brewed Coffee', category: 'Coffee', caffeine: 95, size: 240, icon: Coffee },
  { id: 'd2', name: 'Espresso', category: 'Coffee', caffeine: 64, size: 30, icon: Coffee },
  { id: 'd3', name: 'Latte / Cappuccino', category: 'Coffee', caffeine: 64, size: 240, icon: Coffee },
  { id: 'd9', name: 'Decaf Coffee', category: 'Coffee', caffeine: 7, size: 240, icon: Coffee },
  { id: 'd10', name: 'Cold Brew', category: 'Coffee', caffeine: 200, size: 355, icon: Coffee },
  { id: 'd11', name: 'Instant Coffee', category: 'Coffee', caffeine: 62, size: 240, icon: Coffee },
  { id: 'd12', name: 'Iced Coffee', category: 'Coffee', caffeine: 165, size: 355, icon: Coffee },
  { id: 'd13', name: 'Americano', category: 'Coffee', caffeine: 128, size: 355, icon: Coffee },
  { id: 'd14', name: 'Mocha', category: 'Coffee', caffeine: 80, size: 355, icon: Coffee },
  { id: 'd15', name: 'Macchiato', category: 'Coffee', caffeine: 64, size: 60, icon: Coffee },
  { id: 'd16', name: 'Flat White', category: 'Coffee', caffeine: 130, size: 180, icon: Coffee },
  { id: 'd17', name: 'Nitro Cold Brew', category: 'Coffee', caffeine: 280, size: 355, icon: Coffee },

  // Tea
  { id: 'd4', name: 'Black Tea', category: 'Tea', caffeine: 47, size: 240, icon: Leaf },
  { id: 'd5', name: 'Green Tea', category: 'Tea', caffeine: 28, size: 240, icon: Leaf },
  { id: 'd18', name: 'White Tea', category: 'Tea', caffeine: 15, size: 240, icon: Leaf },
  { id: 'd19', name: 'Oolong Tea', category: 'Tea', caffeine: 37, size: 240, icon: Leaf },
  { id: 'd20', name: 'Matcha Tea', category: 'Tea', caffeine: 70, size: 240, icon: Leaf },
  { id: 'd21', name: 'Iced Tea (Black)', category: 'Tea', caffeine: 25, size: 355, icon: Leaf },
  { id: 'd22', name: 'Chai Tea Latte', category: 'Tea', caffeine: 95, size: 355, icon: Leaf },
  { id: 'd23', name: 'Herbal Tea', category: 'Tea', caffeine: 0, size: 240, icon: Leaf },

  // Soda
  { id: 'd6', name: 'Cola (Generic)', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd24', name: 'Coca-Cola Classic', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd25', name: 'Diet Coke', category: 'Soda', caffeine: 46, size: 355, icon: CupSoda },
  { id: 'd26', name: 'Coke Zero', category: 'Soda', caffeine: 34, size: 355, icon: CupSoda },
  { id: 'd27', name: 'Pepsi', category: 'Soda', caffeine: 38, size: 355, icon: CupSoda },
  { id: 'd28', name: 'Diet Pepsi', category: 'Soda', caffeine: 36, size: 355, icon: CupSoda },
  { id: 'd29', name: 'Dr Pepper', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd30', name: 'Diet Dr Pepper', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd31', name: 'Mountain Dew', category: 'Soda', caffeine: 54, size: 355, icon: CupSoda },
  { id: 'd32', name: 'Diet Mountain Dew', category: 'Soda', caffeine: 54, size: 355, icon: CupSoda },
  { id: 'd33', name: 'Sprite', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'd34', name: '7 Up', category: 'Soda', caffeine: 0, size: 355, icon: CupSoda },
  { id: 'd35', name: 'Sunkist Orange', category: 'Soda', caffeine: 41, size: 355, icon: CupSoda },
  { id: 'd36', name: 'A&W Cream Soda', category: 'Soda', caffeine: 29, size: 355, icon: CupSoda },
  { id: 'd37', name: 'Barq\'s Root Beer', category: 'Soda', caffeine: 22, size: 355, icon: CupSoda },

  // Energy Drinks
  { id: 'd7', name: 'Energy Drink (Generic)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd8', name: 'Energy Shot (Generic)', category: 'Energy Drink', caffeine: 200, size: 60, icon: Zap },
  { id: 'd38', name: 'Red Bull (250ml)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd39', name: 'Red Bull (355ml)', category: 'Energy Drink', caffeine: 114, size: 355, icon: Zap },
  { id: 'd40', name: 'Red Bull Sugarfree (250ml)', category: 'Energy Drink', caffeine: 80, size: 250, icon: Zap },
  { id: 'd41', name: 'Monster Energy (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd42', name: 'Monster Lo-Carb (473ml)', category: 'Energy Drink', caffeine: 140, size: 473, icon: Zap },
  { id: 'd43', name: 'Monster Zero Ultra (473ml)', category: 'Energy Drink', caffeine: 140, size: 473, icon: Zap },
  { id: 'd44', name: 'Rockstar (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd45', name: 'Rockstar Sugar Free (473ml)', category: 'Energy Drink', caffeine: 160, size: 473, icon: Zap },
  { id: 'd46', name: 'Bang Energy (473ml)', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'd47', name: '5-Hour Energy', category: 'Energy Drink', caffeine: 200, size: 57, icon: Zap },
  { id: 'd48', name: '5-Hour Energy Extra Strength', category: 'Energy Drink', caffeine: 230, size: 57, icon: Zap },
  { id: 'd49', name: 'Celsius (355ml)', category: 'Energy Drink', caffeine: 200, size: 355, icon: Zap },
  { id: 'd50', name: 'Reign Total Body Fuel (473ml)', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },
  { id: 'd51', name: 'VPX Bang', category: 'Energy Drink', caffeine: 300, size: 473, icon: Zap },

  // Starbucks (Popular Sizes: Short 236ml, Tall 355ml, Grande 473ml, Venti 591ml)
  { id: 's1', name: 'Starbucks Brewed Coffee (Grande)', category: 'Coffee', caffeine: 310, size: 473, icon: Coffee },
  { id: 's2', name: 'Starbucks Blonde Roast (Grande)', category: 'Coffee', caffeine: 360, size: 473, icon: Coffee },
  { id: 's3', name: 'Starbucks Pike Place (Grande)', category: 'Coffee', caffeine: 310, size: 473, icon: Coffee },
  { id: 's4', name: 'Starbucks Decaf Pike Place (Grande)', category: 'Coffee', caffeine: 25, size: 473, icon: Coffee },
  { id: 's5', name: 'Starbucks Espresso Shot', category: 'Coffee', caffeine: 75, size: 22, icon: Coffee },
  { id: 's6', name: 'Starbucks Caffe Latte (Grande)', category: 'Coffee', caffeine: 150, size: 473, icon: Coffee },
  { id: 's7', name: 'Starbucks Cappuccino (Grande)', category: 'Coffee', caffeine: 150, size: 473, icon: Coffee },
  { id: 's8', name: 'Starbucks Caffe Americano (Grande)', category: 'Coffee', caffeine: 225, size: 473, icon: Coffee },
  { id: 's9', name: 'Starbucks Flat White (Grande)', category: 'Coffee', caffeine: 195, size: 473, icon: Coffee },
  { id: 's10', name: 'Starbucks Caffe Mocha (Grande)', category: 'Coffee', caffeine: 175, size: 473, icon: Coffee },
  { id: 's11', name: 'Starbucks Iced Coffee (Grande)', category: 'Coffee', caffeine: 165, size: 473, icon: Coffee },
  { id: 's12', name: 'Starbucks Cold Brew (Grande)', category: 'Coffee', caffeine: 205, size: 473, icon: Coffee },
  { id: 's13', name: 'Starbucks Nitro Cold Brew (Grande)', category: 'Coffee', caffeine: 280, size: 473, icon: Coffee },
  { id: 's14', name: 'Starbucks Doubleshot on Ice', category: 'Coffee', caffeine: 150, size: 236, icon: Coffee },
  { id: 's15', name: 'Starbucks Frappuccino Coffee (Grande)', category: 'Coffee', caffeine: 95, size: 473, icon: Coffee },
  { id: 's16', name: 'Starbucks Iced Shaken Espresso (Grande)', category: 'Coffee', caffeine: 225, size: 473, icon: Coffee },
  { id: 's17', name: 'Starbucks Chai Tea Latte (Grande)', category: 'Tea', caffeine: 95, size: 473, icon: Leaf },
  { id: 's18', name: 'Starbucks Matcha Tea Latte (Grande)', category: 'Tea', caffeine: 80, size: 473, icon: Leaf },
  { id: 's19', name: 'Starbucks Black Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473, icon: Leaf },
  { id: 's20', name: 'Starbucks Green Iced Tea (Grande)', category: 'Tea', caffeine: 25, size: 473, icon: Leaf },
  { id: 's21', name: 'Starbucks Refresher (Grande)', category: 'Energy Drink', caffeine: 45, size: 473, icon: Zap },

  // Dunkin' (Popular Sizes: Small 296ml, Medium 414ml, Large 591ml)
  { id: 'dunk1', name: 'Dunkin\' Brewed Coffee (Medium)', category: 'Coffee', caffeine: 210, size: 414, icon: Coffee },
  { id: 'dunk2', name: 'Dunkin\' Decaf Coffee (Medium)', category: 'Coffee', caffeine: 10, size: 414, icon: Coffee },
  { id: 'dunk3', name: 'Dunkin\' Americano (Medium)', category: 'Coffee', caffeine: 284, size: 414, icon: Coffee },
  { id: 'dunk4', name: 'Dunkin\' Latte (Medium)', category: 'Coffee', caffeine: 166, size: 414, icon: Coffee },
  { id: 'dunk5', name: 'Dunkin\' Cappuccino (Medium)', category: 'Coffee', caffeine: 166, size: 414, icon: Coffee },
  { id: 'dunk6', name: 'Dunkin\' Espresso Shot', category: 'Coffee', caffeine: 98, size: 30, icon: Coffee },
  { id: 'dunk7', name: 'Dunkin\' Iced Coffee (Medium)', category: 'Coffee', caffeine: 297, size: 710, icon: Coffee },
  { id: 'dunk8', name: 'Dunkin\' Cold Brew (Medium)', category: 'Coffee', caffeine: 260, size: 710, icon: Coffee },
  { id: 'dunk9', name: 'Dunkin\' Frozen Coffee (Medium)', category: 'Coffee', caffeine: 295, size: 710, icon: Coffee },
  { id: 'dunk10', name: 'Dunkin\' Macchiato (Medium)', category: 'Coffee', caffeine: 284, size: 414, icon: Coffee },
  { id: 'dunk11', name: 'Dunkin\' Chai Latte (Medium)', category: 'Tea', caffeine: 108, size: 414, icon: Leaf },

  // McDonald's (Popular Sizes: Small 355ml, Medium 473ml, Large 621ml)
  { id: 'mcd1', name: 'McDonald\'s McCafé Coffee (Medium)', category: 'Coffee', caffeine: 145, size: 473, icon: Coffee },
  { id: 'mcd2', name: 'McDonald\'s Iced Coffee (Medium)', category: 'Coffee', caffeine: 133, size: 473, icon: Coffee },
  { id: 'mcd3', name: 'McDonald\'s Latte (Medium)', category: 'Coffee', caffeine: 142, size: 473, icon: Coffee },
  { id: 'mcd4', name: 'McDonald\'s Americano (Medium)', category: 'Coffee', caffeine: 114, size: 473, icon: Coffee },
  { id: 'mcd5', name: 'McDonald\'s Espresso Shot', category: 'Coffee', caffeine: 71, size: 30, icon: Coffee },
  { id: 'mcd6', name: 'McDonald\'s Frappé (Medium)', category: 'Coffee', caffeine: 130, size: 473, icon: Coffee },
  { id: 'mcd7', name: 'McDonald\'s Sweet Tea (Medium)', category: 'Tea', caffeine: 100, size: 621, icon: Leaf },

  // Other Common Caffeinated Items
  { id: 'oth1', name: 'Dark Chocolate (1 oz / 28g)', category: 'Other', caffeine: 24, size: 28, icon: Beaker },
  { id: 'oth2', name: 'Milk Chocolate (1 oz / 28g)', category: 'Other', caffeine: 6, size: 28, icon: Beaker },
  { id: 'oth3', name: 'Hot Chocolate (240ml)', category: 'Other', caffeine: 5, size: 240, icon: Coffee },
  { id: 'oth4', name: 'Caffeine Pill', category: 'Other', caffeine: 200, size: 1, icon: Pill },
  { id: 'oth5', name: 'Pre-Workout Supplement (1 scoop)', category: 'Other', caffeine: 150, size: 10, icon: Beaker },
  { id: 'oth6', name: 'NoDoz Max Strength', category: 'Other', caffeine: 200, size: 1, icon: Pill },
  { id: 'oth7', name: 'Excedrin Migraine (2 tablets)', category: 'Other', caffeine: 130, size: 2, icon: Pill },
  { id: 'oth8', name: 'Guayaki Yerba Mate (458ml can)', category: 'Tea', caffeine: 150, size: 458, icon: Leaf },
  { id: 'oth9', name: 'Kombucha (240ml)', category: 'Tea', caffeine: 15, size: 240, icon: Leaf },
  { id: 'oth10', name: 'Caffeinated Water (e.g., Water Joe)', category: 'Other', caffeine: 70, size: 500, icon: CupSoda },
  { id: 'oth11', name: 'Clif Shot Energy Gel (with caffeine)', category: 'Other', caffeine: 50, size: 34, icon: Beaker },
];
