
import type { SugarInfo } from './types';

export const sugars: Omit<SugarInfo, 'id'>[] = [
  { name: '28 Black Energy Drink', size_fl_oz: 8.46, calories: 125, sugar_g: 30 },
  { name: '3 Water', size_fl_oz: 16.9, calories: 0, sugar_g: 0 },
  { name: '3D Energy Drink', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: '4 Purpose Energy Drink', size_fl_oz: 8.46, calories: 70, sugar_g: 18 },
  { name: '4C Energy Drink Mix', size_fl_oz: 16.9, calories: 15, sugar_g: 0 },
  { name: '5 Hour Energy', size_fl_oz: 1.93, calories: 4, sugar_g: 0 },
  { name: '5 Hour Energy Extra Strength', size_fl_oz: 1.93, calories: 0, sugar_g: 0 },
  { name: '7 Eleven Brewed Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: '7-Eleven Energy Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: '7-Up', size_fl_oz: 12, calories: 140, sugar_g: 38 },
  { name: 'A Shoc', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'A&W Cream Soda', size_fl_oz: 12, calories: 170, sugar_g: 46 },
  { name: 'A&W Root Beer', size_fl_oz: 12, calories: 170, sugar_g: 46 },
  { name: 'A&W Zero Sugar Cream Soda', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'ABB Turbo Tea Zero', size_fl_oz: 18, calories: 0, sugar_g: 0 },
  { name: 'Accelerator', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Advocare Slam Energy Shot', size_fl_oz: 2, calories: 10, sugar_g: 0 },
  { name: 'Advocare Slim', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Afri Cola', size_fl_oz: 11.16, calories: 139, sugar_g: 35 },
  { name: 'AHA Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Alani Nu Energy Drink', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Ale 8 1', size_fl_oz: 12, calories: 120, sugar_g: 30 },
  { name: 'ALL IN Energy Drink', size_fl_oz: 12, calories: 25, sugar_g: 4 },
  { name: 'Alpine Start Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Alsa Energy Drink Mix', size_fl_oz: 16, calories: 30, sugar_g: 7 },
  { name: 'Americano Coffee', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'AMIN.O. Energy Drink', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'Amino Force Energy Drink', size_fl_oz: 22, calories: 0, sugar_g: 0 },
  { name: 'Arbonne Energy Fizz Stck', size_fl_oz: 8, calories: 15, sugar_g: 2 },
  { name: 'Arby\'s Jamocha Shake', size_fl_oz: 16, calories: 830, sugar_g: 116 },
  { name: 'Arizona Arnold Palmer Half and Half', size_fl_oz: 16.9, calories: 180, sugar_g: 44 },
  { name: 'Arizona Energy Drink Rx', size_fl_oz: 11.5, calories: 130, sugar_g: 30 },
  { name: 'Arizona Iced Tea', size_fl_oz: 16, calories: 190, sugar_g: 47 },
  { name: 'Arti Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'AXIO Energy Drink Mix', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Bai Antioxidant Infusion', size_fl_oz: 18, calories: 10, sugar_g: 1 },
  { name: 'Bai Boost', size_fl_oz: 11.47, calories: 10, sugar_g: 1 },
  { name: 'Balance Active Shot', size_fl_oz: 2, calories: 80, sugar_g: 12 },
  { name: 'Balance Energy Shot', size_fl_oz: 2, calories: 77, sugar_g: 15 },
  { name: 'Bang Energy', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Bang Keto Coffee', size_fl_oz: 16, calories: 130, sugar_g: 1 },
  { name: 'Bang Natural', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Bang Shot', size_fl_oz: 3, calories: 0, sugar_g: 0 },
  { name: 'Bang Sweet Tea', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Barista Bros Iced Coffee', size_fl_oz: 16.91, calories: 204, sugar_g: 20 },
  { name: 'Barqs Red Creme Soda', size_fl_oz: 12, calories: 170, sugar_g: 45 },
  { name: 'Barqs Root Beer', size_fl_oz: 12, calories: 160, sugar_g: 44 },
  { name: 'Baskin Robbins Cappuccino Blast', size_fl_oz: 24, calories: 470, sugar_g: 57 },
  { name: 'Bawls', size_fl_oz: 16, calories: 190, sugar_g: 46 },
  { name: 'BE Beyond Energy Drink', size_fl_oz: 12, calories: 15, sugar_g: 0 },
  { name: 'Beaver Buzz Energy Drink', size_fl_oz: 16, calories: 240, sugar_g: 63 },
  { name: 'BEEBAD Energy Drink', size_fl_oz: 8.46, calories: 110, sugar_g: 28 },
  { name: 'Berocca', size_fl_oz: 8, calories: 5, sugar_g: 0 },
  { name: 'Berzerk Energy Drink Mix', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Best Choice Strawberry Energy Drink Mix', size_fl_oz: 8, calories: 5, sugar_g: 0 },
  { name: 'Big Red Soda', size_fl_oz: 12, calories: 150, sugar_g: 38 },
  { name: 'Big Train Java Chip Ice Coffee', size_fl_oz: 12, calories: 410, sugar_g: 42 },
  { name: 'Big Train Spiced Chai', size_fl_oz: 8, calories: 210, sugar_g: 36 },
  { name: 'Bigelow Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Biggby Brewed Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Biggby Creamy Lattes', size_fl_oz: 16, calories: 387, sugar_g: 50 },
  { name: 'Biggby Espresso', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Biggby Iced Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Biggby Iced Tea', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Bing Energy Drink', size_fl_oz: 12, calories: 30, sugar_g: 5 },
  { name: 'Bizzy Cold Brew', size_fl_oz: 2.67, calories: 0, sugar_g: 0 },
  { name: 'Black Bruin Energy Drink', size_fl_oz: 8.46, calories: 122, sugar_g: 27 },
  { name: 'Black Ink Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Black Insomnia Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Black Label Brewed Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Bloom Energy', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Blu Frog Energy Drink', size_fl_oz: 8.46, calories: 90, sugar_g: 12 },
  { name: 'Blue Bolt (UK)', size_fl_oz: 8.46, calories: 112, sugar_g: 24.6 },
  { name: 'Blue Charge (UK)', size_fl_oz: 8.46, calories: 49, sugar_g: 10 },
  { name: 'Blue Spark (UK)', size_fl_oz: 8.46, calories: 56, sugar_g: 12 },
  { name: 'Bodyarmour Edge', size_fl_oz: 20, calories: 180, sugar_g: 44 },
  { name: 'Bomb Energy Drink', size_fl_oz: 8.46, calories: 0, sugar_g: 28 },
  { name: 'Bomba (EU)', size_fl_oz: 8.4, calories: 123, sugar_g: 28 },
  { name: 'Boost Energy (UK)', size_fl_oz: 8.46, calories: 58, sugar_g: 12.3 },
  { name: 'Boost Nutritional Drink', size_fl_oz: 8, calories: 240, sugar_g: 20 },
  { name: 'Bottled Iced Coffee Dunkin Donuts', size_fl_oz: 13.7, calories: 260, sugar_g: 39 },
  { name: 'BPM Energy Drink', size_fl_oz: 16.91, calories: 290, sugar_g: 70 },
  { name: 'BreinFuel', size_fl_oz: 12, calories: 60, sugar_g: 3 },
  { name: 'Brew Dr Kombucha Uplift', size_fl_oz: 14, calories: 80, sugar_g: 16 },
  { name: 'Brisk Iced Tea', size_fl_oz: 12, calories: 70, sugar_g: 17 },
  { name: 'Brown Rice Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Bubbl\'r Sparkling Water', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'Bubly Bounce Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Bubly Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Bucked Up', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Bulletproof Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Burn Energy Drink', size_fl_oz: 12, calories: 163, sugar_g: 39 },
  { name: 'C4 On The Go', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'C4 Performance Energy', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'C4 Smart Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'C4 Ultimate Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Cafe Bustelo', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Cafe Con Leche', size_fl_oz: 6, calories: 56, sugar_g: 5 },
  { name: 'Caffe Mocha', size_fl_oz: 12, calories: 239, sugar_g: 35 },
  { name: 'Caffe Nero Coffee', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'Califia Farms Cold Brew Coffee', size_fl_oz: 8, calories: 10, sugar_g: 0 },
  { name: 'Canada Dry Green Tea Ginger Ale', size_fl_oz: 12, calories: 140, sugar_g: 35 },
  { name: 'Cannonball Coffee Maximum Charge (UK)', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Cappuccino', size_fl_oz: 12, calories: 97, sugar_g: 8 },
  { name: 'Carabao Energy Drink (UK)', size_fl_oz: 11.16, calories: 63, sugar_g: 15 },
  { name: 'Caribou BOUsted Sparkling Water', size_fl_oz: 11.5, calories: 0, sugar_g: 0 },
  { name: 'Caribou Brewed Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Caribou Canned Cold Brew', size_fl_oz: 11.5, calories: 10, sugar_g: 0 },
  { name: 'Cascara', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'CBD Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Celsius Energy Drink', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Celsius Stevia', size_fl_oz: 12, calories: 15, sugar_g: 0 },
  { name: 'Chai Tea', size_fl_oz: 8, calories: 0, sugar_g: 22 },
  { name: 'Chameleon Cold Brew Coffee', size_fl_oz: 8, calories: 15, sugar_g: 0 },
  { name: 'Chameleon Cold Brew RTD', size_fl_oz: 10, calories: 10, sugar_g: 0 },
  { name: 'Chameleon Cold Brew With Milk', size_fl_oz: 11, calories: 100, sugar_g: 8 },
  { name: 'Cheerwine', size_fl_oz: 12, calories: 150, sugar_g: 42 },
  { name: 'Chick-fil-A Brewed Coffee', size_fl_oz: 10, calories: 0, sugar_g: 0 },
  { name: 'Chick-fil-A Frosted Coffee', size_fl_oz: 14, calories: 240, sugar_g: 38 },
  { name: 'Chick-fil-A Iced Coffee', size_fl_oz: 14, calories: 190, sugar_g: 25 },
  { name: 'Chick-fil-A Iced Tea', size_fl_oz: 16, calories: 120, sugar_g: 30 },
  { name: 'Choffy (roasted cacao)', size_fl_oz: 6, calories: 0, sugar_g: 0 },
  { name: 'Cintron Energy Drink', size_fl_oz: 8.4, calories: 60, sugar_g: 14 },
  { name: 'Clif Shot Energy Gel', size_fl_oz: 1.2, calories: 100, sugar_g: 12 },
  { name: 'Club Mate (EU)', size_fl_oz: 16.91, calories: 160, sugar_g: 32 },
  { name: 'Coca Cola Plus', size_fl_oz: 470, calories: 0, sugar_g: 0 },
  { name: 'Coca-Cola Caffeine Free', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Coca-Cola Cherry', size_fl_oz: 12, calories: 150, sugar_g: 42 },
  { name: 'Coca-Cola Cherry Vanilla', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Coca-Cola Cherry Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Coca-Cola Classic', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Coca-Cola Energy', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Coca-Cola Orange Vanilla', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Coca-Cola Vanilla', size_fl_oz: 12, calories: 150, sugar_g: 42 },
  { name: 'Coca-Cola Vanilla Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Coca-Cola With Coffee', size_fl_oz: 12, calories: 70, sugar_g: 18 },
  { name: 'Coca-Cola Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Cocaine Energy Drink', size_fl_oz: 12, calories: 90, sugar_g: 21 },
  { name: 'Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Coffee (Decaf, Instant)', size_fl_oz: 8, calories: 6, sugar_g: 0 },
  { name: 'Coffee (Instant)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Coffee (Moka Pot)', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Coffee Bean & Tea leaf Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Coffee Friend Brewed Coffee', size_fl_oz: 8.46, calories: 0, sugar_g: 0 },
  { name: 'Coffee Leaf Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'COGO Caffeinated Hot Chocolate', size_fl_oz: 6, calories: 110, sugar_g: 19 },
  { name: 'Cold Brew Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'CoolBrew Coffee', size_fl_oz: 10, calories: 0, sugar_g: 0 },
  { name: 'Costa Coffee', size_fl_oz: 10.14, calories: 222, sugar_g: 8.7 },
  { name: 'Cran Energy Juice', size_fl_oz: 10, calories: 40, sugar_g: 8 },
  { name: 'Crave Energy Drink (UK)', size_fl_oz: 8.43, calories: 10, sugar_g: 0 },
  { name: 'Crio Bru Brewed Cacao', size_fl_oz: 8, calories: 20, sugar_g: 0 },
  { name: 'Crunk Energy Drink', size_fl_oz: 16, calories: 200, sugar_g: 48 },
  { name: 'Crystal Light Energy Mix', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Crystal Light Iced Tea', size_fl_oz: 8, calories: 5, sugar_g: 0 },
  { name: 'Dare Iced Coffee', size_fl_oz: 16.91, calories: 429, sugar_g: 45 },
  { name: 'Dark Dog Organic Energy', size_fl_oz: 12, calories: 110, sugar_g: 26 },
  { name: 'Death Wish Canned Cold Brew', size_fl_oz: 8, calories: 15, sugar_g: 0 },
  { name: 'Death Wish Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Death Wish Latte', size_fl_oz: 8, calories: 170, sugar_g: 29 },
  { name: 'Decaf Coffee', size_fl_oz: 8, calories: 2, sugar_g: 0 },
  { name: 'Demon Energy Drink', size_fl_oz: 16.91, calories: 253, sugar_g: 58 },
  { name: 'Diet Barqs Root Beer', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Cheerwine', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Coke', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Coke with Splenda', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Dr Pepper', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Mountain Dew', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Pepsi', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet RC Cola', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Diet Wild Cherry Pepsi', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'doc Soda', size_fl_oz: 12, calories: 150, sugar_g: 40 },
  { name: 'Double Cola', size_fl_oz: 12, calories: 160, sugar_g: 39 },
  { name: 'Dr Pepper', size_fl_oz: 12, calories: 150, sugar_g: 41 },
  { name: 'Dr Pepper 10', size_fl_oz: 12, calories: 10, sugar_g: 3 },
  { name: 'Dr Pepper Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Dr Shasta Soda', size_fl_oz: 12, calories: 0, sugar_g: 30 },
  { name: 'Driftaway Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Dripdash Kyoto Coffee', size_fl_oz: 6, calories: 0, sugar_g: 0 },
  { name: 'Duff Energy Drink', size_fl_oz: 12, calories: 170, sugar_g: 42 },
  { name: 'Dunkin Donuts Shot In The Dark', size_fl_oz: 8.1, calories: 80, sugar_g: 13 },
  { name: 'Dunkin Sparkd Energy', size_fl_oz: 32, calories: 170, sugar_g: 37 },
  { name: 'Dunkin\' Cold Brew', size_fl_oz: 24, calories: 5, sugar_g: 0 },
  { name: 'Dunkin\' Donuts Brewed Coffee', size_fl_oz: 14, calories: 5, sugar_g: 0 },
  { name: 'Dunkin\' Donuts Dunkaccino', size_fl_oz: 14, calories: 350, sugar_g: 38 },
  { name: 'Dunkin\' Donuts Extra Charged Coffee', size_fl_oz: 14, calories: 10, sugar_g: 0 },
  { name: 'Dunkin\' Donuts Iced Coffee', size_fl_oz: 24, calories: 5, sugar_g: 2 },
  { name: 'Dunkin\' Donuts Iced Latte', size_fl_oz: 24, calories: 100, sugar_g: 14 },
  { name: 'Dunkin\' Donuts Iced Tea', size_fl_oz: 24, calories: 230, sugar_g: 58 },
  { name: 'Dunkin\' Donuts Latte', size_fl_oz: 14, calories: 100, sugar_g: 14 },
  { name: 'Dutch Bros Blue Rebel Energy Drink', size_fl_oz: 8.4, calories: 160, sugar_g: 37 },
  { name: 'Dutch Bros Coffee (Classic)', size_fl_oz: 20, calories: 10, sugar_g: 0 },
  { name: 'DynaPep', size_fl_oz: 0.14, calories: 0, sugar_g: 0 },
  { name: 'E6 Energy Shot', size_fl_oz: 1.93, calories: 0, sugar_g: 0 },
  { name: 'EBOOST Energy Drink Mix', size_fl_oz: 8, calories: 5, sugar_g: 0 },
  { name: 'EBOOST Super Fuel', size_fl_oz: 12, calories: 20, sugar_g: 2 },
  { name: 'EBOOST Workout Crusher Mix', size_fl_oz: 8, calories: 40, sugar_g: 2 },
  { name: 'Eight O\'Clock Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Einstein Bros Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Electric Monkey Wild Energy Drink', size_fl_oz: 16, calories: 220, sugar_g: 56 },
  { name: 'EnerBee Energy Drink', size_fl_oz: 12, calories: 80, sugar_g: 16 },
  { name: 'Equip Pure Energy Shot', size_fl_oz: 1.8, calories: 35, sugar_g: 7 },
  { name: 'Espresso Monster', size_fl_oz: 8.4, calories: 170, sugar_g: 24 },
  { name: 'Espresso Shot', size_fl_oz: 1.5, calories: 0, sugar_g: 0 },
  { name: 'Eternal Energy Extra Strength', size_fl_oz: 1.93, calories: 0, sugar_g: 0 },
  { name: 'Eternal Energy Shot', size_fl_oz: 1.93, calories: 0, sugar_g: 0 },
  { name: 'Euro Shopper Energy Drink (EU)', size_fl_oz: 8.46, calories: 115, sugar_g: 28 },
  { name: 'F3 Energy', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Fakeer Energy Drink (EU)', size_fl_oz: 12.52, calories: 148, sugar_g: 41 },
  { name: 'Fanta', size_fl_oz: 12, calories: 160, sugar_g: 44 },
  { name: 'Fast Lane Black Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Faxe Kondi', size_fl_oz: 11.16, calories: 135, sugar_g: 33 },
  { name: 'Faygo Cola', size_fl_oz: 12, calories: 165, sugar_g: 43.5 },
  { name: 'Faygo Moon Mist', size_fl_oz: 12, calories: 150, sugar_g: 36 },
  { name: 'Flat White', size_fl_oz: 12, calories: 170, sugar_g: 13 },
  { name: 'Folgers Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Forto Organic Coffee Shot', size_fl_oz: 2, calories: 35, sugar_g: 7 },
  { name: 'Freeway Cola', size_fl_oz: 11.16, calories: 135, sugar_g: 34 },
  { name: 'Fresca', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Fritz Kola (EU)', size_fl_oz: 11.16, calories: 135, sugar_g: 36 },
  { name: 'Full Throttle Energy Drink', size_fl_oz: 16, calories: 220, sugar_g: 58 },
  { name: 'Fuze Iced Tea', size_fl_oz: 24, calories: 160, sugar_g: 44 },
  { name: 'Gamer Supps GG Energy Mix', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Gatorade Bolt 24 Energize', size_fl_oz: 16.9, calories: 40, sugar_g: 9 },
  { name: 'Gatorade Fast Twitch', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'GFuel Cans', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'GFuel Energy Drink Mix', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'Ghost Energy Drink', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Ginger Ale', size_fl_oz: 12, calories: 140, sugar_g: 35 },
  { name: 'Gloria Jean\'s Coffee', size_fl_oz: 2.028, calories: 0, sugar_g: 0 },
  { name: 'Go Fast Energy Drink', size_fl_oz: 16, calories: 200, sugar_g: 50 },
  { name: 'Go Fast High Octane Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Go Girl Energy Drink', size_fl_oz: 12, calories: 25, sugar_g: 4 },
  { name: 'Goat Fuel', size_fl_oz: 12, calories: 15, sugar_g: 0 },
  { name: 'Gold Peak Coffee', size_fl_oz: 8, calories: 5, sugar_g: 0 },
  { name: 'Gold Peak Tea', size_fl_oz: 18.5, calories: 0, sugar_g: 0 },
  { name: 'Gothrider Gasoline Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Gourmesso Coffee Pods', size_fl_oz: 1.35, calories: 0, sugar_g: 0 },
  { name: 'Great Value Energy Drink Enhancers', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Great Value Energy Drink Mix', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Greek Coffee (Metrios)', size_fl_oz: 2, calories: 25, sugar_g: 5 },
  { name: 'Green Cola', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Gridlock Energy Drink', size_fl_oz: 16, calories: 200, sugar_g: 54 },
  { name: 'Guayaki Canned Yerba Mate', size_fl_oz: 15.5, calories: 120, sugar_g: 28 },
  { name: 'Guayaki Yerba Mate Bottled Tea', size_fl_oz: 16, calories: 80, sugar_g: 18 },
  { name: 'Guayusa Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'GURU Energy Drink', size_fl_oz: 12, calories: 115, sugar_g: 30 },
  { name: 'GURU Sparkling Energy Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'GymBrew Coffee', size_fl_oz: 12, calories: 4, sugar_g: 0 },
  { name: 'Half Caff Folgers', size_fl_oz: 6, calories: 0, sugar_g: 0 },
  { name: 'Hell Energy Coffee', size_fl_oz: 8.46, calories: 150, sugar_g: 22.5 },
  { name: 'Hell Energy Drink (EU)', size_fl_oz: 8.46, calories: 115, sugar_g: 27 },
  { name: 'Heroec Energy Water', size_fl_oz: 16.9, calories: 0, sugar_g: 0 },
  { name: 'Hi Ball Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 25 },
  { name: 'HICAF Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'High Brew Coffee', size_fl_oz: 8, calories: 50, sugar_g: 6 },
  { name: 'High Voltage Coffee (AU)', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Hint Caffeine Kick Water', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Honest Iced Tea', size_fl_oz: 16.9, calories: 70, sugar_g: 19 },
  { name: 'Hot6 the King Energy', size_fl_oz: 12, calories: 15, sugar_g: 0 },
  { name: 'Hyde Xtreme', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Hype Energy Drink (EU)', size_fl_oz: 8.46, calories: 108, sugar_g: 25 },
  { name: 'IBC Root Beer', size_fl_oz: 12, calories: 160, sugar_g: 40 },
  { name: 'Illy Issimo Cafe', size_fl_oz: 6.8, calories: 45, sugar_g: 10 },
  { name: 'Inca Kola', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Indulgio Cappuccino', size_fl_oz: 8, calories: 79, sugar_g: 5 },
  { name: 'Inko\'s White Tea Energy', size_fl_oz: 15.5, calories: 100, sugar_g: 24 },
  { name: 'International Delight Iced Coffee', size_fl_oz: 12, calories: 180, sugar_g: 29 },
  { name: 'Irn Bru (UK)', size_fl_oz: 11.16, calories: 65, sugar_g: 16 },
  { name: 'Java Kick Coffee Cola', size_fl_oz: 12, calories: 130, sugar_g: 32 },
  { name: 'Java Monster', size_fl_oz: 15, calories: 220, sugar_g: 35 },
  { name: 'Java Monster 300', size_fl_oz: 15, calories: 200, sugar_g: 32 },
  { name: 'Javvy Coffee Concentrate', size_fl_oz: 6, calories: 5, sugar_g: 0 },
  { name: 'Joker Mad Energy', size_fl_oz: 16, calories: 260, sugar_g: 64 },
  { name: 'Jolt Cola', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Juice Monster', size_fl_oz: 16, calories: 160, sugar_g: 37 },
  { name: 'Juvee', size_fl_oz: 12, calories: 5, sugar_g: 0 },
  { name: 'K Cup Decaf', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'K Cup Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'K-Cup Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Kaffn8 Liquified Caffeine', size_fl_oz: 0.25, calories: 0, sugar_g: 0 },
  { name: 'Kickapoo Soda: Joy Juice & Fruit Shine', size_fl_oz: 12, calories: 190, sugar_g: 48 },
  { name: 'Kill Cliff Energy X Recover', size_fl_oz: 12, calories: 20, sugar_g: 0 },
  { name: 'Kill Cliff Ignite', size_fl_oz: 12, calories: 25, sugar_g: 0 },
  { name: 'Killer Coffee (AU)', size_fl_oz: 8.46, calories: 0, sugar_g: 0 },
  { name: 'Kin Spritz', size_fl_oz: 8, calories: 25, sugar_g: 5 },
  { name: 'Kirkland Energy Shot', size_fl_oz: 2, calories: 5, sugar_g: 0 },
  { name: 'KOE Kombucha', size_fl_oz: 12, calories: 35, sugar_g: 8 },
  { name: 'Kombucha Tea', size_fl_oz: 8, calories: 30, sugar_g: 6 },
  { name: 'Kona Gold Energy Drink', size_fl_oz: 12, calories: 150, sugar_g: 40 },
  { name: 'La Colombe Cold Brew', size_fl_oz: 9, calories: 5, sugar_g: 1 },
  { name: 'La Colombe Draft Latte', size_fl_oz: 9, calories: 90, sugar_g: 10 },
  { name: 'La Croix Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Latte', size_fl_oz: 16, calories: 160, sugar_g: 20 },
  { name: 'LevlUp Gaming Booster', size_fl_oz: 16.91, calories: 8, sugar_g: 2 },
  { name: 'Limitless Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Lipton Iced Tea', size_fl_oz: 20, calories: 110, sugar_g: 29 },
  { name: 'Lipton Natural Energy Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Lipton Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Liquid Death Iced Tea', size_fl_oz: 19.2, calories: 30, sugar_g: 6 },
  { name: 'Liquid Help Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Liquid Ice Energy Drink', size_fl_oz: 8.3, calories: 120, sugar_g: 28 },
  { name: 'Liquid IV Energy', size_fl_oz: 16, calories: 45, sugar_g: 11 },
  { name: 'Live+ Energy Drink', size_fl_oz: 16.9, calories: 227, sugar_g: 52.5 },
  { name: 'Long Black', size_fl_oz: 6, calories: 2, sugar_g: 0 },
  { name: 'Lucozade', size_fl_oz: 12.85, calories: 133, sugar_g: 17 },
  { name: 'LYFT Energy Mix', size_fl_oz: 8, calories: 4, sugar_g: 1 },
  { name: 'M-150 Energy Drink', size_fl_oz: 8.46, calories: 155, sugar_g: 38 },
  { name: 'Mamma Chia Energy', size_fl_oz: 10, calories: 110, sugar_g: 3 },
  { name: 'Mana Energy Potion', size_fl_oz: 1.69, calories: 25, sugar_g: 0 },
  { name: 'Marquis Energy Drink', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Master Brew Kombucha', size_fl_oz: 15.2, calories: 60, sugar_g: 16 },
  { name: 'Matcha Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'MATI Energy Drink', size_fl_oz: 12, calories: 90, sugar_g: 17 },
  { name: 'Maxwell House Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Maxwell House Max Boost Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'McDonalds (McCafe) Latte', size_fl_oz: 16, calories: 190, sugar_g: 15 },
  { name: 'McDonalds (McCafe) Mocha', size_fl_oz: 16, calories: 380, sugar_g: 52 },
  { name: 'McDonalds Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'McDonalds Iced Coffee', size_fl_oz: 11.5, calories: 190, sugar_g: 25 },
  { name: 'McDonalds Sweet Tea', size_fl_oz: 32, calories: 160, sugar_g: 38 },
  { name: 'Mega Monster Energy Drink', size_fl_oz: 24, calories: 320, sugar_g: 81 },
  { name: 'Mello Yello', size_fl_oz: 12, calories: 170, sugar_g: 47 },
  { name: 'Meltdown Ketone Drink', size_fl_oz: 12, calories: 18, sugar_g: 0 },
  { name: 'MiO Energy Water Enhancer', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Monster Assault', size_fl_oz: 16, calories: 210, sugar_g: 50 },
  { name: 'Monster Dragon Tea', size_fl_oz: 23, calories: 100, sugar_g: 23 },
  { name: 'Monster Energy', size_fl_oz: 16, calories: 210, sugar_g: 54 },
  { name: 'Monster Hydro', size_fl_oz: 25.4, calories: 150, sugar_g: 33 },
  { name: 'Monster Import', size_fl_oz: 18.6, calories: 190, sugar_g: 49 },
  { name: 'Monster Killer Brew', size_fl_oz: 15, calories: 220, sugar_g: 35 },
  { name: 'Monster Lo-Carb', size_fl_oz: 16, calories: 30, sugar_g: 6 },
  { name: 'Monster Mango Loco', size_fl_oz: 16, calories: 240, sugar_g: 55 },
  { name: 'Monster Mule', size_fl_oz: 16, calories: 210, sugar_g: 52 },
  { name: 'Monster Nitro', size_fl_oz: 16, calories: 220, sugar_g: 51 },
  { name: 'Monster Pipeline Punch', size_fl_oz: 16, calories: 190, sugar_g: 46 },
  { name: 'Monster Rehab', size_fl_oz: 15.5, calories: 25, sugar_g: 4 },
  { name: 'Monster Reserve', size_fl_oz: 16, calories: 120, sugar_g: 28 },
  { name: 'Monster Ripper Energy Juice (UK)', size_fl_oz: 16.91, calories: 185, sugar_g: 42 },
  { name: 'Monster The Doctor VR46 (UK)', size_fl_oz: 16.91, calories: 219, sugar_g: 52 },
  { name: 'Monster Tour Water', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Monster Ultra', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Monster Zero Sugar', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Moose Juice Energy Drink', size_fl_oz: 16.94, calories: 0, sugar_g: 0 },
  { name: 'Morning Thunder Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Mother Energy Drink', size_fl_oz: 16.91, calories: 228, sugar_g: 51 },
  { name: 'Mount Hagen Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Mountain Dew', size_fl_oz: 12, calories: 170, sugar_g: 46 },
  { name: 'Mountain Dew Amp', size_fl_oz: 16, calories: 220, sugar_g: 58 },
  { name: 'Mountain Dew Baja Blast', size_fl_oz: 12, calories: 170, sugar_g: 44 },
  { name: 'Mountain Dew Code Red', size_fl_oz: 12, calories: 170, sugar_g: 46 },
  { name: 'Mountain Dew Energy', size_fl_oz: 16, calories: 25, sugar_g: 4 },
  { name: 'Mountain Dew Game Fuel', size_fl_oz: 16, calories: 90, sugar_g: 23 },
  { name: 'Mountain Dew Kickstart', size_fl_oz: 16, calories: 80, sugar_g: 20 },
  { name: 'Mountain Dew Live Wire', size_fl_oz: 12, calories: 180, sugar_g: 46 },
  { name: 'Mountain Dew Major Melon', size_fl_oz: 12, calories: 160, sugar_g: 44 },
  { name: 'Mountain Dew Spark', size_fl_oz: 12, calories: 170, sugar_g: 55 },
  { name: 'Mountain Dew Voltage', size_fl_oz: 12, calories: 170, sugar_g: 46 },
  { name: 'Mountain Dew Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Moxie Soda', size_fl_oz: 12, calories: 140, sugar_g: 37 },
  { name: 'Mucho Mango Energy Drink', size_fl_oz: 8, calories: 100, sugar_g: 23 },
  { name: 'Mug Root Beer', size_fl_oz: 12, calories: 160, sugar_g: 43 },
  { name: 'Muscle Milk Coffee House', size_fl_oz: 11, calories: 130, sugar_g: 0 },
  { name: 'Muscle Monster', size_fl_oz: 15, calories: 180, sugar_g: 9 },
  { name: 'Mushroom Coffee', size_fl_oz: 8, calories: 10, sugar_g: 0 },
  { name: 'Nerd Focus', size_fl_oz: 12, calories: 170, sugar_g: 42 },
  { name: 'Nescafe 3 in 1 Instant Coffee', size_fl_oz: 6, calories: 74, sugar_g: 9.2 },
  { name: 'Nescafe Dolce Gusto', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Nescafe Gold', size_fl_oz: 8.46, calories: 0, sugar_g: 0 },
  { name: 'Nescafe Ice Java', size_fl_oz: 8, calories: 50, sugar_g: 11 },
  { name: 'Nescafe Ricoffy', size_fl_oz: 8, calories: 10, sugar_g: 1 },
  { name: 'Nespresso Coffee Capsules', size_fl_oz: 1.35, calories: 0, sugar_g: 0 },
  { name: 'Nestea Iced Tea', size_fl_oz: 16.9, calories: 160, sugar_g: 43 },
  { name: 'Nestle Milo', size_fl_oz: 8, calories: 80, sugar_g: 9 },
  { name: 'Neu Nootropic Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Neuro Sonic', size_fl_oz: 14.5, calories: 35, sugar_g: 9 },
  { name: 'NOCCO Energy Drink (EU)', size_fl_oz: 11.17, calories: 0, sugar_g: 0 },
  { name: 'Noocaf Smart Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'NOS Energy Drink', size_fl_oz: 16, calories: 200, sugar_g: 54 },
  { name: 'Nutramint Smart Serum', size_fl_oz: 2, calories: 45, sugar_g: 4 },
  { name: 'Nuun Sport', size_fl_oz: 16, calories: 15, sugar_g: 1 },
  { name: 'OCA Energy Drink', size_fl_oz: 12, calories: 60, sugar_g: 9 },
  { name: 'Ocean Spray Brew', size_fl_oz: 8, calories: 30, sugar_g: 6 },
  { name: 'Octane Energy Drink Mix', size_fl_oz: 12, calories: 25, sugar_g: 0 },
  { name: 'Oi Ocha Green Tea', size_fl_oz: 16.9, calories: 5, sugar_g: 0 },
  { name: 'Oikos Pro Fuel', size_fl_oz: 10, calories: 130, sugar_g: 13 },
  { name: 'OK Energy Drink', size_fl_oz: 8.45, calories: 113, sugar_g: 27.5 },
  { name: 'OLIPOP Vintage Cola', size_fl_oz: 12, calories: 35, sugar_g: 2 },
  { name: 'Orange Crush', size_fl_oz: 12, calories: 160, sugar_g: 43 },
  { name: 'Oregon Chai Tea', size_fl_oz: 6, calories: 130, sugar_g: 31 },
  { name: 'Pacific Chai', size_fl_oz: 6, calories: 90, sugar_g: 14 },
  { name: 'Panera Bread Coffee', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'PC Cola', size_fl_oz: 12, calories: 150, sugar_g: 39 },
  { name: 'PC Cola Diet', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Peace Tea', size_fl_oz: 23, calories: 150, sugar_g: 39 },
  { name: 'Peet\'s Brewed Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Peet\'s Caffe Americano', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Peet\'s Caffe Latte', size_fl_oz: 16, calories: 190, sugar_g: 18 },
  { name: 'Peet\'s Caffe Mocha', size_fl_oz: 16, calories: 390, sugar_g: 39 },
  { name: 'Peet\'s Cappuccino', size_fl_oz: 16, calories: 140, sugar_g: 12 },
  { name: 'Peet\'s Coffee Espresso', size_fl_oz: 1.5, calories: 0, sugar_g: 0 },
  { name: 'Peet\'s Decaf Espresso', size_fl_oz: 1.5, calories: 0, sugar_g: 0 },
  { name: 'Peet\'s Iced Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Peet\'s Iced Latte', size_fl_oz: 16, calories: 120, sugar_g: 9 },
  { name: 'Peet\'s Iced Mocha', size_fl_oz: 16, calories: 310, sugar_g: 29 },
  { name: 'Pep Talk Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Pepsi', size_fl_oz: 12, calories: 150, sugar_g: 41 },
  { name: 'Pepsi Caffeine Free', size_fl_oz: 12, calories: 150, sugar_g: 41 },
  { name: 'Pepsi Made With Sugar', size_fl_oz: 12, calories: 150, sugar_g: 40 },
  { name: 'Pepsi Max (UK)', size_fl_oz: 11.16, calories: 0, sugar_g: 0 },
  { name: 'Pepsi Zero Sugar', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Performance Caffeine', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'PerformElite Pre-Workout', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Perk Energy Beverage', size_fl_oz: 8, calories: 90, sugar_g: 0 },
  { name: 'Perrier Energize', size_fl_oz: 8.46, calories: 35, sugar_g: 7 },
  { name: 'Perrier Sparkling Water', size_fl_oz: 11.15, calories: 0, sugar_g: 0 },
  { name: 'PG Tips Black Tea', size_fl_oz: 6.78, calories: 0, sugar_g: 0 },
  { name: 'Phocus Sparkling Water', size_fl_oz: 11.5, calories: 0, sugar_g: 0 },
  { name: 'Phoenix Energy Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Pibb Xtra', size_fl_oz: 12, calories: 140, sugar_g: 39 },
  { name: 'Poland Spring Sparkling Energy Water', size_fl_oz: 11.5, calories: 35, sugar_g: 7 },
  { name: 'Polar Frost Plus Energy', size_fl_oz: 17, calories: 10, sugar_g: 2 },
  { name: 'Polar Seltzer Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Poppi Soda Classic Cola', size_fl_oz: 12, calories: 25, sugar_g: 5 },
  { name: 'Power Horse Energy Drink (EU)', size_fl_oz: 8.45, calories: 125, sugar_g: 21.5 },
  { name: 'Premier Protein Cafe Latte', size_fl_oz: 11.5, calories: 160, sugar_g: 1 },
  { name: 'Premium Cola (EU)', size_fl_oz: 11.16, calories: 132, sugar_g: 33 },
  { name: 'Prime Energy Drink', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Private Selection Canned Espresso', size_fl_oz: 15, calories: 230, sugar_g: 28 },
  { name: 'Propel Zero Powder', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Proper Wild Energy Shot', size_fl_oz: 2.5, calories: 25, sugar_g: 5 },
  { name: 'Protein2O + Energy', size_fl_oz: 16.91, calories: 70, sugar_g: 0 },
  { name: 'Pure Boost Energy Drink Mix', size_fl_oz: 16, calories: 25, sugar_g: 0 },
  { name: 'Pure Cofain 699 (EU)', size_fl_oz: 8.46, calories: 148, sugar_g: 36 },
  { name: 'Pure Kick Energy Drink Mix', size_fl_oz: 16.9, calories: 10, sugar_g: 0 },
  { name: 'Pure Leaf Iced Tea', size_fl_oz: 18.5, calories: 160, sugar_g: 42 },
  { name: 'Purity Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Quake Energy Berry Blast Slurpee', size_fl_oz: 16, calories: 5, sugar_g: 1 },
  { name: 'Quake Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Rambler Energy Drink', size_fl_oz: 16, calories: 60, sugar_g: 12 },
  { name: 'Raze Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'RC (Royal Crown) Cola', size_fl_oz: 12, calories: 160, sugar_g: 43 },
  { name: 'Red Bull', size_fl_oz: 8.46, calories: 117, sugar_g: 27 },
  { name: 'Red Bull Editions', size_fl_oz: 8.46, calories: 113, sugar_g: 28 },
  { name: 'Red Bull Simply Cola', size_fl_oz: 8.46, calories: 0, sugar_g: 0 },
  { name: 'Red Bull Sugarfree', size_fl_oz: 8.46, calories: 10, sugar_g: 0 },
  { name: 'Red Bull Zero', size_fl_oz: 8.46, calories: 0, sugar_g: 0 },
  { name: 'Red Devil Energy Drink', size_fl_oz: 16, calories: 0, sugar_g: 37 },
  { name: 'Red Eye Energy Drink', size_fl_oz: 11.1, calories: 149, sugar_g: 36 },
  { name: 'Red Power Elixir', size_fl_oz: 12, calories: 160, sugar_g: 28 },
  { name: 'Red Thunder Energy Drink', size_fl_oz: 12, calories: 156, sugar_g: 37 },
  { name: 'Red Thunder Energy Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Red Thunder Extra Strength', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Redline Max 300', size_fl_oz: 2.5, calories: 0, sugar_g: 0 },
  { name: 'Redline Princess', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Redline Xtreme Energy Drink', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Redline Xtreme Shot', size_fl_oz: 3, calories: 5, sugar_g: 0 },
  { name: 'Reed\'s Ginger Energize Shot', size_fl_oz: 2, calories: 24, sugar_g: 6 },
  { name: 'Reign Storm', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Reign Total Body Fuel', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Revv Coffee Pods', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Riot Energy', size_fl_oz: 16, calories: 80, sugar_g: 16 },
  { name: 'Rip It Energy Drink', size_fl_oz: 16, calories: 260, sugar_g: 66 },
  { name: 'Rip It Energy Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Rise Nitro Cold Brew Coffee', size_fl_oz: 10, calories: 10, sugar_g: 0 },
  { name: 'Ritz Cola', size_fl_oz: 12, calories: 144, sugar_g: 36 },
  { name: 'Roaring Lion Energy Drink', size_fl_oz: 8, calories: 100, sugar_g: 25 },
  { name: 'Robusta Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Rockstar Boom', size_fl_oz: 16, calories: 280, sugar_g: 66 },
  { name: 'Rockstar Energy Drink (Original)', size_fl_oz: 16, calories: 250, sugar_g: 63 },
  { name: 'Rockstar Halo Infinite', size_fl_oz: 16, calories: 250, sugar_g: 61 },
  { name: 'Rockstar Juiced', size_fl_oz: 16, calories: 30, sugar_g: 4 },
  { name: 'Rockstar Organic Energy Drink', size_fl_oz: 15, calories: 180, sugar_g: 46 },
  { name: 'Rockstar Punched', size_fl_oz: 16, calories: 260, sugar_g: 61 },
  { name: 'Rockstar Pure Zero', size_fl_oz: 16, calories: 20, sugar_g: 0 },
  { name: 'Rockstar Recovery', size_fl_oz: 16, calories: 25, sugar_g: 2 },
  { name: 'Rockstar Sugar Free', size_fl_oz: 16, calories: 25, sugar_g: 0 },
  { name: 'Rockstar Thermo', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Rockstar Unplugged', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Rockstar XDurance', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Rockstar Zero Carb', size_fl_oz: 16, calories: 25, sugar_g: 0 },
  { name: 'Rogue Energy Drink', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Rogue Energy Drink Mix', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'RootJack Caffeinated Pirate Root Beer', size_fl_oz: 12, calories: 200, sugar_g: 47 },
  { name: 'Rowdy Energy Drink', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Ruby Red Squirt', size_fl_oz: 12, calories: 170, sugar_g: 45 },
  { name: 'Runa', size_fl_oz: 12, calories: 0, sugar_g: 2 },
  { name: 'Rush! Energy Drink', size_fl_oz: 8.3, calories: 120, sugar_g: 31 },
  { name: 'Ryse Fuel', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Sambazon Amazon Energy Drink', size_fl_oz: 12, calories: 120, sugar_g: 29 },
  { name: 'Sarsaparilla', size_fl_oz: 12, calories: 170, sugar_g: 41 },
  { name: 'Scheckters Energy Drink', size_fl_oz: 8.46, calories: 78, sugar_g: 17.5 },
  { name: 'Score Energy Drink Gorilla', size_fl_oz: 16.91, calories: 240, sugar_g: 33.5 },
  { name: 'Screamin Energy Max Hit', size_fl_oz: 0.61, calories: 40, sugar_g: 9 },
  { name: 'Seattle\'s Best Brewed Coffee', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Sencha Green Tea Shot', size_fl_oz: 6.4, calories: 0, sugar_g: 0 },
  { name: 'Shasta Cola', size_fl_oz: 12, calories: 170, sugar_g: 42 },
  { name: 'Shasta Diet Cola', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Shasta Mountain Rush', size_fl_oz: 12, calories: 150, sugar_g: 36 },
  { name: 'Ski Soda', size_fl_oz: 12, calories: 180, sugar_g: 46.5 },
  { name: 'Slammers Energy Drink (EU)', size_fl_oz: 8.46, calories: 122, sugar_g: 28.5 },
  { name: 'SlimFast Shake - Cappuccino', size_fl_oz: 11, calories: 180, sugar_g: 1 },
  { name: 'Slurpee', size_fl_oz: 12, calories: 90, sugar_g: 24 },
  { name: 'Snapple Tea', size_fl_oz: 16, calories: 150, sugar_g: 36 },
  { name: 'Sneak Energy Drink Mix', size_fl_oz: 16, calories: 12, sugar_g: 0 },
  { name: 'SoBe Energy Citrus', size_fl_oz: 20, calories: 250, sugar_g: 63 },
  { name: 'SoBe Green Tea', size_fl_oz: 20, calories: 200, sugar_g: 51 },
  { name: 'Soda Stream', size_fl_oz: 8, calories: 40, sugar_g: 10 },
  { name: 'Solimo Energy Drink', size_fl_oz: 16, calories: 10, sugar_g: 0 },
  { name: 'Source 1899 (UK)', size_fl_oz: 8.46, calories: 58, sugar_g: 12 },
  { name: 'Southern Sweet Tea', size_fl_oz: 16, calories: 128, sugar_g: 32 },
  { name: 'Soylent Stacked', size_fl_oz: 11.16, calories: 180, sugar_g: 3 },
  { name: 'Spark Energy Drink Mix', size_fl_oz: 8, calories: 15, sugar_g: 0 },
  { name: 'Sparkling Ice Caffeine', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Sparkling Ice Energy', size_fl_oz: 12, calories: 15, sugar_g: 3 },
  { name: 'Speed Energy Fuel', size_fl_oz: 16, calories: 240, sugar_g: 54 },
  { name: 'Spider Energy Drink', size_fl_oz: 16, calories: 120, sugar_g: 28 },
  { name: 'Spike Energy Double Shot', size_fl_oz: 4.26, calories: 0, sugar_g: 0 },
  { name: 'Spike Hardcore Energy', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Spike Shooter', size_fl_oz: 12, calories: 10, sugar_g: 0 },
  { name: 'Sprecher Cherry Cola', size_fl_oz: 16, calories: 240, sugar_g: 54 },
  { name: 'Sprite', size_fl_oz: 12, calories: 140, sugar_g: 38 },
  { name: 'Squirt Soda', size_fl_oz: 12, calories: 140, sugar_g: 38 },
  { name: 'Stacker Extreme Energy Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Starbucks 2X Coffee Pods', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Starbucks Bottled Iced Coffee', size_fl_oz: 48, calories: 240, sugar_g: 48 },
  { name: 'Starbucks Canned Nitro Cold Brew', size_fl_oz: 11, calories: 0, sugar_g: 0 },
  { name: 'Starbucks Caramel Macchiato', size_fl_oz: 16, calories: 250, sugar_g: 33 },
  { name: 'Starbucks Cold & Crafted', size_fl_oz: 11, calories: 50, sugar_g: 10 },
  { name: 'Starbucks Cold Brew Bottled', size_fl_oz: 11, calories: 50, sugar_g: 10 },
  { name: 'Starbucks Cold Brew Canned', size_fl_oz: 11, calories: 120, sugar_g: 17 },
  { name: 'Starbucks Cold Brew Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Starbucks Cordusio Mocha', size_fl_oz: 8, calories: 130, sugar_g: 12 },
  { name: 'Starbucks Decaf Coffee', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'Starbucks Doubleshot Energy', size_fl_oz: 15, calories: 220, sugar_g: 29 },
  { name: 'Starbucks Doubleshot Espresso', size_fl_oz: 6.5, calories: 140, sugar_g: 18 },
  { name: 'Starbucks Frappuccino (Bottled)', size_fl_oz: 13.7, calories: 300, sugar_g: 47 },
  { name: 'Starbucks Grande Caffe Americano', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'Starbucks Grande Caffe Latte', size_fl_oz: 16, calories: 190, sugar_g: 18 },
  { name: 'Starbucks Grande Caffe Mocha', size_fl_oz: 16, calories: 370, sugar_g: 35 },
  { name: 'Starbucks Grande Cappuccino', size_fl_oz: 16, calories: 140, sugar_g: 12 },
  { name: 'Starbucks Grande Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Starbucks Iced Americano', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'Starbucks Iced Espresso Classics', size_fl_oz: 12, calories: 190, sugar_g: 30 },
  { name: 'Starbucks Nitro Cold Brew Coffee', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Starbucks Pink Drink', size_fl_oz: 16, calories: 140, sugar_g: 24 },
  { name: 'Starbucks Pumpkin Cream Cold Brew', size_fl_oz: 16, calories: 250, sugar_g: 31 },
  { name: 'Starbucks Refreshers', size_fl_oz: 16, calories: 70, sugar_g: 14 },
  { name: 'Starbucks Refreshers Canned', size_fl_oz: 12, calories: 90, sugar_g: 19 },
  { name: 'Starbucks Triple Shot Energy', size_fl_oz: 15, calories: 210, sugar_g: 29 },
  { name: 'Starbucks Verismo Coffee Pods', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Starbucks Via Ready Brew', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Steaz Energy', size_fl_oz: 12, calories: 140, sugar_g: 35 },
  { name: 'Steep 18 Cold Brew', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Sting Energy Drink', size_fl_oz: 8.455, calories: 70, sugar_g: 22 },
  { name: 'Stipe Miocic Extra Strength Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Stok Coffee Shots', size_fl_oz: 0.43, calories: 10, sugar_g: 0 },
  { name: 'Stok Cold Brew', size_fl_oz: 13.7, calories: 0, sugar_g: 0 },
  { name: 'Strike Force Energy Drink Mix', size_fl_oz: 16.91, calories: 0, sugar_g: 0 },
  { name: 'Stumptown Cold Brew Coffee', size_fl_oz: 10.5, calories: 3, sugar_g: 0 },
  { name: 'Stumptown Nitro Cold Brew', size_fl_oz: 11, calories: 3, sugar_g: 0 },
  { name: 'Sudden Instant Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Sun Drop Soda', size_fl_oz: 12, calories: 170, sugar_g: 45 },
  { name: 'Sunkist Orange Soda', size_fl_oz: 12, calories: 160, sugar_g: 44 },
  { name: 'Sunup Pure Green Coffee', size_fl_oz: 11, calories: 5, sugar_g: 0 },
  { name: 'T-Virus Antidote', size_fl_oz: 12, calories: 160, sugar_g: 40 },
  { name: 'Taft Coffee (EU)', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Taiwanese Milk Tea', size_fl_oz: 16, calories: 299, sugar_g: 38 },
  { name: 'Taster\'s Choice Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Taurus Energy Drink', size_fl_oz: 8.46, calories: 180, sugar_g: 40 },
  { name: 'Tazo Chai', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Black)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Decaf)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Green)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Herbal)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Iced)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Instant)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Jasmine)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (Oolong)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tea (White)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Teas\' Tea Oolong', size_fl_oz: 16.9, calories: 0, sugar_g: 0 },
  { name: 'Teavana Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Tejava Iced Tea', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'TENZING Natural Energy', size_fl_oz: 8.46, calories: 50, sugar_g: 11 },
  { name: 'Tiger Energy Drink', size_fl_oz: 8.46, calories: 0, sugar_g: 27 },
  { name: 'Tim Hortons Large Brewed Coffee', size_fl_oz: 20, calories: 5, sugar_g: 0 },
  { name: 'Tim Hortons Small French Vanilla Coffee', size_fl_oz: 10, calories: 0, sugar_g: 31 },
  { name: 'Tonic Water', size_fl_oz: 10, calories: 110, sugar_g: 27 },
  { name: 'Triton Energy Drink', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'Tropicana Twister Soda', size_fl_oz: 20, calories: 320, sugar_g: 87.5 },
  { name: 'Tru Energy Wakeup', size_fl_oz: 12, calories: 10, sugar_g: 2 },
  { name: 'TruBrain Extra', size_fl_oz: 1, calories: 25, sugar_g: 4 },
  { name: 'True Lemon Energy Mix', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'TrueStart Performance Coffee', size_fl_oz: 5.1, calories: 0, sugar_g: 0 },
  { name: 'Turkey Hill Iced Tea', size_fl_oz: 12, calories: 120, sugar_g: 30 },
  { name: 'Turkish Coffee', size_fl_oz: 2, calories: 20, sugar_g: 5 },
  { name: 'Tweaker Energy Drink', size_fl_oz: 8.46, calories: 110, sugar_g: 27 },
  { name: 'Tweaker Shot', size_fl_oz: 2, calories: 0, sugar_g: 0 },
  { name: 'Twig Tea (Kukicha)', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Ugly Energy Water', size_fl_oz: 16, calories: 0, sugar_g: 0 },
  { name: 'UPTIME Energy Drink', size_fl_oz: 12, calories: 150, sugar_g: 37 },
  { name: 'USANA Rev3 Energy Drink', size_fl_oz: 12, calories: 105, sugar_g: 16 },
  { name: 'V Iced Coffee', size_fl_oz: 16.91, calories: 345, sugar_g: 45 },
  { name: 'V Energy Drink', size_fl_oz: 8.45, calories: 116, sugar_g: 26.5 },
  { name: 'V8 +Energy Drink', size_fl_oz: 8, calories: 140, sugar_g: 0 },
  { name: 'Venom Death Adder', size_fl_oz: 16, calories: 160, sugar_g: 40 },
  { name: 'Vernors Ginger Ale', size_fl_oz: 12, calories: 140, sugar_g: 38 },
  { name: 'Very Strong Coffee', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Virtue Clean Energy Beverage', size_fl_oz: 8.46, calories: 8, sugar_g: 0 },
  { name: 'Viso Energy Drink', size_fl_oz: 17, calories: 140, sugar_g: 35 },
  { name: 'Vital 4U Liquid Energy', size_fl_oz: 0.5, calories: 34, sugar_g: 7 },
  { name: 'VitaminWater Energy', size_fl_oz: 20, calories: 100, sugar_g: 27 },
  { name: 'VitaRain Zero Enhanced Water', size_fl_oz: 20, calories: 0, sugar_g: 0 },
  { name: 'Voila Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Vuum', size_fl_oz: 12, calories: 50, sugar_g: 0 },
  { name: 'Waka Decaf Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Waka Indian Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Waka Instant Coffee', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Waka Instant Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Water Joe', size_fl_oz: 20, calories: 0, sugar_g: 0 },
  { name: 'Wave Soda', size_fl_oz: 12, calories: 25, sugar_g: 5 },
  { name: 'Wawa Coffee', size_fl_oz: 16, calories: 4, sugar_g: 0 },
  { name: 'Wendy\'s Iced Tea', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Whipped (Dalgona) Coffee', size_fl_oz: 8, calories: 48, sugar_g: 12 },
  { name: 'Wide Awake Coffee Cold Brew', size_fl_oz: 11, calories: 5, sugar_g: 0 },
  { name: 'Wide Awake Energy Coffee', size_fl_oz: 15, calories: 190, sugar_g: 31 },
  { name: 'Wide Awake Iced Coffee Drinks', size_fl_oz: 13.7, calories: 290, sugar_g: 44 },
  { name: 'Wild Cherry Pepsi', size_fl_oz: 12, calories: 160, sugar_g: 42 },
  { name: 'Wild Tiger Energy Drink', size_fl_oz: 8.36, calories: 125, sugar_g: 10 },
  { name: 'Wildcat Energy Drink (UK)', size_fl_oz: 8.46, calories: 115, sugar_g: 28 },
  { name: 'Wired X 3000 Energy Drink', size_fl_oz: 16, calories: 220, sugar_g: 52 },
  { name: 'Wired X Berry Rush', size_fl_oz: 16, calories: 220, sugar_g: 52 },
  { name: 'Wired X344 Energy Drink', size_fl_oz: 16, calories: 220, sugar_g: 50 },
  { name: 'Woke Up Energy Shot', size_fl_oz: 1.93, calories: 0, sugar_g: 0 },
  { name: 'X Ray Energy Drink', size_fl_oz: 8.46, calories: 125, sugar_g: 30 },
  { name: 'X-Mode Energy Shot', size_fl_oz: 1, calories: 0, sugar_g: 0 },
  { name: 'Xing Craft Brew', size_fl_oz: 16, calories: 5, sugar_g: 0 },
  { name: 'Xingtea Iced Green Tea', size_fl_oz: 23.5, calories: 50, sugar_g: 13 },
  { name: 'XL Energy Drink (EU)', size_fl_oz: 8.45, calories: 118, sugar_g: 28 },
  { name: 'XS Energy Drink', size_fl_oz: 8.4, calories: 10, sugar_g: 0 },
  { name: 'Xyience Energy Drink', size_fl_oz: 16, calories: 15, sugar_g: 0 },
  { name: 'Yellow Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Yerba Mate Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Yerbae Sparkling Water', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'YMateina Yerba Mate', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Zest Highly Caffeinated Tea', size_fl_oz: 8, calories: 0, sugar_g: 0 },
  { name: 'Zest Sparkling Tea', size_fl_oz: 12, calories: 60, sugar_g: 14 },
  { name: 'Zevia Cola', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'Zevia Energy Drink', size_fl_oz: 12, calories: 0, sugar_g: 0 },
  { name: 'ZipFizz Energy Drink Mix', size_fl_oz: 16, calories: 20, sugar_g: 0 },
  { name: 'Zoa Energy Drink', size_fl_oz: 16, calories: 100, sugar_g: 23 },
  { name: 'Zola Coconut Water Espresso', size_fl_oz: 17.5, calories: 0, sugar_g: 28 },
  { name: 'Zombie Blood Energy Potion', size_fl_oz: 3.4, calories: 25, sugar_g: 7 }
];
